1. Data Understanding

In [1]:
#install library kaggle untuk mengakses dataset dari Kaggle
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [2]:
import kagglehub
# Download latest version
path = kagglehub.dataset_download("mahdimashayekhi/disease-risk-from-daily-habits")
print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mahdimashayekhi/disease-risk-from-daily-habits/1.archive...

100%|██████████| 20.8M/20.8M [00:00<00:00, 154MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/mahdimashayekhi/disease-risk-from-daily-habits/versions/1

In [3]:
#install library catboost untuk model machine learning
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.3 MB/s eta 0:00:000:00:0100:01
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [4]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

In [5]:
# mengecek file yang telah di download
print(os.listdir(path))

['health_lifestyle_classification.csv']

In [6]:
# Membaca dataset
df = pd.read_csv(path + "/health_lifestyle_classification.csv")
df.head()

,survey_code,age,gender,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,...,sunlight_exposure,meals_per_day,caffeine_intake,family_history,pet_owner,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage,target
0,1,56,Male,173.416872,56.886640,18.915925,18.915925,56.747776,18.989117,72.165130,...,High,5,Moderate,No,Yes,0,1.0,5.5,-2.275502,healthy
1,2,69,Female,163.207380,97.799859,36.716278,36.716278,110.148833,36.511417,85.598889,...,High,5,High,Yes,No,0,1.0,5.5,6.239340,healthy
2,3,46,Male,177.281966,80.687562,25.673050,25.673050,77.019151,25.587429,90.295030,...,High,4,Moderate,No,No,0,1.0,5.5,5.423737,healthy
3,4,32,Female,172.101255,63.142868,21.318480,21.318480,63.955440,21.177109,100.504211,...,High,1,NaN,No,Yes,0,1.0,5.5,8.388611,healthy
4,5,60,Female,163.608816,40.000000,14.943302,14.943302,44.829907,14.844299,69.021150,...,High,1,High,Yes,Yes,0,1.0,5.5,0.332622,healthy

In [7]:
# mengecek jumlah baris dan kolom pada dataset
print("data shape : ", df.shape)

data shape :  (100000, 48)

In [8]:
# Mengecek informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            92331 non-null   float64
 11  heart_rate                85997 non-null   float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   84164 non-null   float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               91671 non-null   float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       57613 non-null   object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    91530 non-null   float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             75031 non-null   object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           66739 non-null   object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          89526 non-null   float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB

In [9]:
# describe dataset untuk melihat statistik dasar dari dataset
df.describe()

,survey_code,age,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,blood_pressure,...,water_intake,screen_time,stress_level,mental_health_score,income,meals_per_day,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,92331.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,91530.000000,100000.000000,100000.0,89526.0,100000.0,100000.000000
mean,50000.500000,48.525990,170.023707,70.064862,24.493876,24.493876,73.481627,24.494140,84.933043,119.980149,...,2.006373,6.021525,4.991600,5.004680,4038.127284,2.998720,0.0,1.0,5.5,0.015726
std,28867.657797,17.886768,9.982798,14.693667,5.951069,5.951069,17.853206,5.954184,12.040314,15.015503,...,0.688868,2.933835,3.154997,3.164228,1930.025678,1.414786,0.0,0.0,0.0,5.764489
min,1.000000,18.000000,140.000000,40.000000,9.988495,9.988495,29.965484,9.893845,34.093185,59.128168,...,0.500000,0.000000,0.000000,0.000000,500.000000,1.000000,0.0,1.0,5.5,-9.999895
25%,25000.750000,33.000000,163.306615,59.856938,20.271405,20.271405,60.814215,20.271059,76.795185,109.812060,...,1.532011,3.971318,2.000000,2.000000,2665.402843,2.000000,0.0,1.0,5.5,-4.980501
50%,50000.500000,48.000000,170.016778,69.924141,24.156734,24.156734,72.470201,24.151699,84.957139,119.951794,...,2.000659,5.991171,5.000000,5.000000,4004.601345,3.000000,0.0,1.0,5.5,0.015589
75%,75000.250000,64.000000,176.728920,80.027418,28.258696,28.258696,84.776088,28.247648,93.018713,130.120621,...,2.473047,8.024470,8.000000,8.000000,5360.012694,4.000000,0.0,1.0,5.5,5.008424
max,100000.000000,79.000000,210.000000,139.250894,59.234792,59.234792,177.704377,59.142646,133.153631,184.439195,...,5.000000,16.000000,10.000000,10.000000,12029.409353,5.000000,0.0,1.0,5.5,9.999966

2. Cleaning Data

# missing value

In [10]:
# Mengecek nilai yang hilang
missing_values = df.isnull().sum()

print("missing value per kolom : ")
print(missing_values[missing_values>0])

missing value per kolom :
blood_pressure          7669
heart_rate             14003
insulin                15836
daily_steps             8329
alcohol_consumption    42387
income                  8470
exercise_type          24969
caffeine_intake        33261
gene_marker_flag       10474
dtype: int64

In [11]:
# Mengecek persentase nilai yang hilang
missing_percentage = df.isnull().mean().sort_values(ascending=False)*100
print("percentage of missing values per column : ")
print(missing_percentage[missing_percentage>0])

percentage of missing values per column :
alcohol_consumption    42.387
caffeine_intake        33.261
exercise_type          24.969
insulin                15.836
heart_rate             14.003
gene_marker_flag       10.474
income                  8.470
daily_steps             8.329
blood_pressure          7.669
dtype: float64

In [12]:
# Mengecek jumlah nilai yang hilang per kolom
print("Jumlah Missing Value tiap kolom:\n")

print(df.isna().sum())

Jumlah Missing Value tiap kolom:

survey_code                     0
age                             0
gender                          0
height                          0
weight                          0
bmi                             0
bmi_estimated                   0
bmi_scaled                      0
bmi_corrected                   0
waist_size                      0
blood_pressure               7669
heart_rate                  14003
cholesterol                     0
glucose                         0
insulin                     15836
sleep_hours                     0
sleep_quality                   0
work_hours                      0
physical_activity               0
daily_steps                  8329
calorie_intake                  0
sugar_intake                    0
alcohol_consumption         42387
smoking_level                   0
water_intake                    0
screen_time                     0
stress_level                    0
mental_health_score             0
mental_health_support           0
education_level                 0
job_type                        0
occupation                      0
income                       8470
diet_type                       0
exercise_type               24969
device_usage                    0
healthcare_access               0
insurance                       0
sunlight_exposure               0
meals_per_day                   0
caffeine_intake             33261
family_history                  0
pet_owner                       0
electrolyte_level               0
gene_marker_flag            10474
environmental_risk_score        0
daily_supplement_dosage         0
target                          0
dtype: int64

In [13]:
# Mengecek jumlah nilai yang hilang secara keseluruhan dataset
df.isna().sum().sum()

np.int64(165398)

In [14]:
# Mengisi nilai yang hilang dengan median untuk kolom numerik dan modus untuk kolom kategorikal

# 1) Kolom numerik
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    df[col] = df[col].fillna(
        df[col].median()
    )

# 2) Kolom kategorikal
cat_cols = df.select_dtypes(
    include='object'
).columns

for col in cat_cols:
    df[col] = df[col].fillna(
        "Unknown"
    )

In [15]:
(df.isna().sum()/len(df))*100

survey_code                 0.0
age                         0.0
gender                      0.0
height                      0.0
weight                      0.0
bmi                         0.0
bmi_estimated               0.0
bmi_scaled                  0.0
bmi_corrected               0.0
waist_size                  0.0
blood_pressure              0.0
heart_rate                  0.0
cholesterol                 0.0
glucose                     0.0
insulin                     0.0
sleep_hours                 0.0
sleep_quality               0.0
work_hours                  0.0
physical_activity           0.0
daily_steps                 0.0
calorie_intake              0.0
sugar_intake                0.0
alcohol_consumption         0.0
smoking_level               0.0
water_intake                0.0
screen_time                 0.0
stress_level                0.0
mental_health_score         0.0
mental_health_support       0.0
education_level             0.0
job_type                    0.0
occupation                  0.0
income                      0.0
diet_type                   0.0
exercise_type               0.0
device_usage                0.0
healthcare_access           0.0
insurance                   0.0
sunlight_exposure           0.0
meals_per_day               0.0
caffeine_intake             0.0
family_history              0.0
pet_owner                   0.0
electrolyte_level           0.0
gene_marker_flag            0.0
environmental_risk_score    0.0
daily_supplement_dosage     0.0
target                      0.0
dtype: float64

In [16]:
df.isna().sum().sum()

np.int64(0)

In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            100000 non-null  float64
 11  heart_rate                100000 non-null  float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   100000 non-null  float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               100000 non-null  float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       100000 non-null  object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    100000 non-null  float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             100000 non-null  object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           100000 non-null  object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          100000 non-null  float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB
None

# cek duplikat

In [18]:
# Mengecek duplikasi data
df.duplicated().sum()

np.int64(0)

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

In [20]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

In [21]:
# ============================================================
# CEK DUPLICATE DATA
# ============================================================

# Total duplicate
total_duplicate = df.duplicated().sum()

print("Total Duplicate:", total_duplicate)

# Persentase duplicate
duplicate_percent = (
    total_duplicate / len(df)
) * 100

print(
    "Persentase Duplicate:",
    round(duplicate_percent, 2),
    "%"
)

# ============================================================
# TAMPILKAN DATA DUPLICATE
# ============================================================

duplicate_rows = df[
    df.duplicated(keep=False)
]

print("\nData Duplicate:\n")

print(duplicate_rows)

# ============================================================
# JUMLAH ROW DUPLICATE
# ============================================================

print(
    "\nJumlah Row Duplicate:",
    duplicate_rows.shape[0]
)

Total Duplicate: 0
Persentase Duplicate: 0.0 %

Data Duplicate:

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

[0 rows x 48 columns]

Jumlah Row Duplicate: 0

In [22]:
df.head()

,survey_code,age,gender,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,...,sunlight_exposure,meals_per_day,caffeine_intake,family_history,pet_owner,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage,target
0,1,56,Male,173.416872,56.886640,18.915925,18.915925,56.747776,18.989117,72.165130,...,High,5,Moderate,No,Yes,0,1.0,5.5,-2.275502,healthy
1,2,69,Female,163.207380,97.799859,36.716278,36.716278,110.148833,36.511417,85.598889,...,High,5,High,Yes,No,0,1.0,5.5,6.239340,healthy
2,3,46,Male,177.281966,80.687562,25.673050,25.673050,77.019151,25.587429,90.295030,...,High,4,Moderate,No,No,0,1.0,5.5,5.423737,healthy
3,4,32,Female,172.101255,63.142868,21.318480,21.318480,63.955440,21.177109,100.504211,...,High,1,Unknown,No,Yes,0,1.0,5.5,8.388611,healthy
4,5,60,Female,163.608816,40.000000,14.943302,14.943302,44.829907,14.844299,69.021150,...,High,1,High,Yes,Yes,0,1.0,5.5,0.332622,healthy

3. Cek Tipe Data

In [23]:
# Mengecek tipe data setiap kolom
print(df.dtypes)

survey_code                   int64
age                           int64
gender                       object
height                      float64
weight                      float64
bmi                         float64
bmi_estimated               float64
bmi_scaled                  float64
bmi_corrected               float64
waist_size                  float64
blood_pressure              float64
heart_rate                  float64
cholesterol                 float64
glucose                     float64
insulin                     float64
sleep_hours                 float64
sleep_quality                object
work_hours                  float64
physical_activity           float64
daily_steps                 float64
calorie_intake              float64
sugar_intake                float64
alcohol_consumption          object
smoking_level                object
water_intake                float64
screen_time                 float64
stress_level                  int64
mental_health_score           int64
mental_health_support        object
education_level              object
job_type                     object
occupation                   object
income                      float64
diet_type                    object
exercise_type                object
device_usage                 object
healthcare_access            object
insurance                    object
sunlight_exposure            object
meals_per_day                 int64
caffeine_intake              object
family_history               object
pet_owner                    object
electrolyte_level             int64
gene_marker_flag            float64
environmental_risk_score    float64
daily_supplement_dosage     float64
target                       object
dtype: object

In [24]:
# Mengecek nilai unik pada setiap kolom kategorikal
for col in df.select_dtypes(include='object'):

    print(f"\n===== {col} =====")

    print(df[col].unique())

===== gender =====
['Male' 'Female']

===== sleep_quality =====
['Fair' 'Good' 'Poor' 'Excellent']

===== alcohol_consumption =====
['Unknown' 'Regularly' 'Occasionally']

===== smoking_level =====
['Non-smoker' 'Light' 'Heavy']

===== mental_health_support =====
['No' 'Yes']

===== education_level =====
['PhD' 'High School' 'Master' 'Bachelor']

===== job_type =====
['Tech' 'Office' 'Labor' 'Unemployed' 'Service' 'Healthcare']

===== occupation =====
['Farmer' 'Engineer' 'Teacher' 'Doctor' 'Driver' 'Artist']

===== diet_type =====
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']

===== exercise_type =====
['Strength' 'Cardio' 'Mixed' 'Unknown']

===== device_usage =====
['High' 'Moderate' 'Low']

===== healthcare_access =====
['Poor' 'Moderate' 'Good']

===== insurance =====
['No' 'Yes']

===== sunlight_exposure =====
['High' 'Low' 'Moderate']

===== caffeine_intake =====
['Moderate' 'High' 'Unknown']

===== family_history =====
['No' 'Yes']

===== pet_owner =====
['Yes' 'No']

===== target =====
['healthy' 'diseased']

In [25]:
# mengecek semua isi tabel untuk memastikan tidak ada nilai yang aneh atau tidak konsisten

# Tampilkan semua kolom
pd.set_option('display.max_columns', None)

# Lebar tampilan terminal
pd.set_option('display.width', 1000)

# Panjang isi kolom tidak dipotong
pd.set_option('display.max_colwidth', None)

# Tampilkan semua baris jika diperlukan
pd.set_option('display.max_rows', None)

In [26]:
df.head()

   survey_code  age  gender      height     weight        bmi  bmi_estimated  bmi_scaled  bmi_corrected  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level  mental_health_score mental_health_support education_level    job_type occupation       income   diet_type exercise_type device_usage healthcare_access insurance sunlight_exposure  meals_per_day caffeine_intake family_history pet_owner  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage   target
0            1   56    Male  173.416872  56.886640  18.915925      18.915925   56.747776      18.989117   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887             Unknown    Non-smoker      1.694262     5.003963             2                    8                    No             PhD        Tech     Farmer  6759.821719       Vegan      Strength         High              Poor        No              High              5        Moderate             No       Yes                  0               1.0                       5.5                -2.275502  healthy
1            2   69  Female  163.207380  97.799859  36.716278      36.716278  110.148833      36.511417   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3                    9                    No     High School      Office   Engineer  6240.517690       Vegan        Cardio     Moderate          Moderate        No              High              5            High            Yes        No                  0               1.0                       5.5                 6.239340  healthy
2            3   46    Male  177.281966  80.687562  25.673050      25.673050   77.019151      25.587429   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0                    1                    No          Master      Office    Teacher  3429.179266       Vegan        Cardio         High              Good       Yes              High              4        Moderate             No        No                  0               1.0                       5.5                 5.423737  healthy
3            4   32  Female  172.101255  63.142868  21.318480      21.318480   63.955440      21.177109  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10                    4                    No          Master       Labor    Teacher  2618.503534  Vegetarian         Mixed          Low          Moderate        No              High              1         Unknown             No       Yes                  0               1.0                       5.5                 8.388611  healthy
4            5   60  Female  163.608816  40.000000  14.943302      14.943302   44.829907      14.844299   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322             Unknown         Heavy      1.968393     3.180087             9                    7                   Yes          Master  Unemployed     Doctor  3662.086276       Vegan       Unknown          Low          Moderate       Yes              High              1            High            Yes       Yes                  0               1.0                       5.5                 0.332622  healthy

In [27]:
cat_cols = [
    'gender',
    'diet_type',
    'exercise_type',
    'smoking_level'
]

for col in cat_cols:
    df[col] = df[col].astype(str)



for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("="*50)

gender
['Male' 'Female']
==================================================
diet_type
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']
==================================================
exercise_type
['Strength' 'Cardio' 'Mixed' 'Unknown']
==================================================
smoking_level
['Non-smoker' 'Light' 'Heavy']
==================================================

In [28]:
df.describe()

         survey_code            age         height         weight            bmi  bmi_estimated     bmi_scaled  bmi_corrected     waist_size  blood_pressure     heart_rate    cholesterol        glucose        insulin    sleep_hours     work_hours  physical_activity    daily_steps  calorie_intake   sugar_intake   water_intake    screen_time   stress_level  mental_health_score         income  meals_per_day  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage
count  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000      100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000        100000.000000  100000.000000  100000.000000           100000.0          100000.0                  100000.0            100000.000000
mean    50000.500000      48.525990     170.023707      70.064862      24.493876      24.493876      73.481627      24.494140      84.933043      119.977974      74.979964     189.966438      99.994538      14.987491       7.002008       8.001331           3.038344    7012.206098     2201.428579      60.047165       2.006373       6.021525       4.991600             5.004680    4035.287636       2.998720                0.0               1.0                       5.5                 0.015726
std     28867.657797      17.886768       9.982798      14.693667       5.951069       5.951069      17.853206       5.954184      12.040314       14.428246       9.219394      29.981934      19.982828       4.589596       1.496821       1.994723           1.884475    2383.082319      400.516318      19.966850       0.688868       2.933835       3.154997             3.164228    1846.503636       1.414786                0.0               0.0                       0.0                 5.764489
min         1.000000      18.000000     140.000000      40.000000       9.988495       9.988495      29.965484       9.893845      34.093185       59.128168      34.745092      58.410902      12.434931      -6.794483       3.000000       0.000000           0.000000    1000.000000      527.172360     -27.882444       0.500000       0.000000       0.000000             0.000000     500.000000       1.000000                0.0               1.0                       5.5                -9.999895
25%     25000.750000      33.000000     163.306615      59.856938      20.271405      20.271405      60.814215      20.271059      76.795185      110.815119      69.543894     169.667738      86.461401      12.324714       5.986781       6.651093           1.633799    5500.327842     1932.278165      46.504292       1.532011       3.971318       2.000000             2.000000    2796.061969       2.000000                0.0               1.0                       5.5                -4.980501
50%     50000.500000      48.000000     170.016778      69.924141      24.156734      24.156734      72.470201      24.151699      84.957139      119.951794      75.046211     190.044579      99.986834      14.983414       6.998164       8.004549           2.971222    7004.285450     2200.992765      60.047905       2.000659       5.991171       5.000000             5.000000    4004.601345       3.000000                0.0               1.0                       5.5                 0.015589
75%     75000.250000      64.000000     176.728920      80.027418      28.258696      28.258696      84.776088      28.247648      93.018713      129.185145      80.467128     210.222005     113.508722      17.663430       8.019219       9.353669           4.326500    8523.819577     2471.218160      73.476386       2.473047       8.024470       8.000000             8.000000    5219.230324       4.000000                0.0               1.0                       5.5                 5.008424
max    100000.000000      79.000000     210.000000     139.250894      59.234792      59.234792     177.704377      59.142646     133.153631      184.439195     114.136041     319.875613     183.883548      35.464749      12.000000      16.000000          11.631898   18064.969543     3949.019017     141.514522       5.000000      16.000000      10.000000            10.000000   12029.409353       5.000000                0.0               1.0                       5.5                 9.999966

In [29]:
print(df['target'].value_counts())
 
print(df['target'].value_counts(normalize=True))

target
healthy     70097
diseased    29903
Name: count, dtype: int64
target
healthy     0.70097
diseased    0.29903
Name: proportion, dtype: float64

In [30]:
# Menghapus kolom yang tidak diperlukan 
df = df.drop(columns=[
'survey_code',
'bmi_estimated','bmi_scaled','bmi_corrected',
'mental_health_score','mental_health_support',
'education_level','job_type','occupation',
'income','healthcare_access','insurance',
'sunlight_exposure','family_history','pet_owner',
'electrolyte_level','gene_marker_flag',
'environmental_risk_score','daily_supplement_dosage'
])

Feature engineering

In [31]:
# Encode target
df['target'] = df['target'].map({
    'healthy': 0,
    'diseased': 1
})

In [32]:
X = df.drop('target', axis=1)
y = df['target']

In [33]:
print(df.select_dtypes(include='object').columns)

Index(['gender', 'sleep_quality', 'alcohol_consumption', 'smoking_level', 'diet_type', 'exercise_type', 'device_usage', 'caffeine_intake'], dtype='object')

Encoding Kategorikal

In [34]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Cari semua kolom object
cat_cols = df.select_dtypes(include='object').columns

# Encode semua kolom object
for col in cat_cols:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

In [35]:
cat_features = X.select_dtypes(include='object').columns.tolist()

In [36]:
df.head()

   age  gender      height     weight        bmi  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours  sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake  alcohol_consumption  smoking_level  water_intake  screen_time  stress_level  diet_type  exercise_type  device_usage  meals_per_day  caffeine_intake  target
0   56       1  173.416872  56.886640  18.915925   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885              1    7.671313           0.356918  13320.942595     2673.546960     44.476887                    2              2      1.694262     5.003963             2          2              2             0              5                1       0
1   69       0  163.207380  97.799859  36.716278   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410              2    9.515198           0.568219  11911.201401     2650.376972     74.663405                    1              1      0.716409     5.925455             3          2              0             2              5                0       0
2   46       1  177.281966  80.687562  25.673050   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164              3    5.829853           3.764406   2974.035375     1746.755144     19.702382                    1              0      2.487900     4.371250             0          2              0             0              4                1       0
3   32       0  172.101255  63.142868  21.318480  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316              2    9.489693           0.889474   5321.539497     2034.193242     82.580050                    0              0      2.643335     4.116064            10          3              1             1              1                2       0
4   60       0  163.608816  40.000000  14.943302   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514              2    7.275450           2.901608   9791.376712     2386.210257     45.961322                    2              0      1.968393     3.180087             9          2              3             1              1                0       0

In [37]:
df['target'].value_counts()

target
0    70097
1    29903
Name: count, dtype: int64

In [38]:
# ============================================================
# SPLIT DATA
# ============================================================

from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [39]:
# Mengecek data sebelum split
print(x_train.shape)

(80000, 28)

Mengatasi Imbalanced Data

In [40]:
# ============================================================
# INSTALL
# ============================================================

!pip install imbalanced-learn

# ============================================================
# IMPORT
# ============================================================

from imblearn.over_sampling import RandomOverSampler

# ============================================================
# CEK DISTRIBUSI SEBELUM
# ============================================================

print("Distribusi target sebelum Oversampling:\n")

print(y_train.value_counts())

# ============================================================
# OVERSAMPLING
# ============================================================

oversample = RandomOverSampler(
    sampling_strategy='auto',
    random_state=42
)

x_train_over, y_train_over = oversample.fit_resample(
    x_train,
    y_train
)

# ============================================================
# CEK DISTRIBUSI SETELAH
# ============================================================

print("\nDistribusi target setelah Oversampling:\n")

print(y_train_over.value_counts())

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)
Distribusi target sebelum Oversampling:

target
0    56078
1    23922
Name: count, dtype: int64

Distribusi target setelah Oversampling:

target
1    56078
0    56078
Name: count, dtype: int64

In [41]:
# Mengecek data setelah oversampling
print(x_train_over.shape)

(112156, 28)

Train Data

In [42]:
cat_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.03,
    depth=5,
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42
)

cat_model.fit(
    x_train_over,
    y_train_over
)

0:	learn: 0.5194057	total: 82.1ms	remaining: 1m 22s
1:	learn: 0.5386363	total: 113ms	remaining: 56.3s
2:	learn: 0.5282857	total: 141ms	remaining: 46.8s
3:	learn: 0.5321310	total: 169ms	remaining: 42.2s
4:	learn: 0.5293138	total: 198ms	remaining: 39.5s
5:	learn: 0.5272677	total: 228ms	remaining: 37.8s
6:	learn: 0.5324448	total: 257ms	remaining: 36.5s
7:	learn: 0.5353877	total: 291ms	remaining: 36.1s
8:	learn: 0.5377315	total: 322ms	remaining: 35.5s
9:	learn: 0.5412145	total: 353ms	remaining: 35s
10:	learn: 0.5422102	total: 384ms	remaining: 34.5s
11:	learn: 0.5439112	total: 413ms	remaining: 34s
12:	learn: 0.5445343	total: 441ms	remaining: 33.5s
13:	learn: 0.5476458	total: 472ms	remaining: 33.2s
14:	learn: 0.5502250	total: 503ms	remaining: 33s
15:	learn: 0.5505592	total: 537ms	remaining: 33s
16:	learn: 0.5513756	total: 567ms	remaining: 32.8s
17:	learn: 0.5505230	total: 600ms	remaining: 32.8s
18:	learn: 0.5514588	total: 632ms	remaining: 32.6s
19:	learn: 0.5485306	total: 671ms	remaining: 32.9s
20:	learn: 0.5481519	total: 711ms	remaining: 33.2s
21:	learn: 0.5476525	total: 756ms	remaining: 33.6s
22:	learn: 0.5498465	total: 787ms	remaining: 33.4s
23:	learn: 0.5505024	total: 817ms	remaining: 33.2s
24:	learn: 0.5472217	total: 847ms	remaining: 33s
25:	learn: 0.5477526	total: 878ms	remaining: 32.9s
26:	learn: 0.5486743	total: 908ms	remaining: 32.7s
27:	learn: 0.5502207	total: 941ms	remaining: 32.7s
28:	learn: 0.5494143	total: 969ms	remaining: 32.5s
29:	learn: 0.5485865	total: 999ms	remaining: 32.3s
30:	learn: 0.5495516	total: 1.03s	remaining: 32.2s
31:	learn: 0.5505806	total: 1.06s	remaining: 32s
32:	learn: 0.5532244	total: 1.09s	remaining: 31.9s
33:	learn: 0.5529332	total: 1.12s	remaining: 31.8s
34:	learn: 0.5541769	total: 1.15s	remaining: 31.8s
35:	learn: 0.5541122	total: 1.18s	remaining: 31.7s
36:	learn: 0.5528392	total: 1.21s	remaining: 31.6s
37:	learn: 0.5527194	total: 1.27s	remaining: 32.1s
38:	learn: 0.5536336	total: 1.32s	remaining: 32.6s
39:	learn: 0.5530605	total: 1.38s	remaining: 33.1s
40:	learn: 0.5537232	total: 1.44s	remaining: 33.6s
41:	learn: 0.5537071	total: 1.49s	remaining: 33.9s
42:	learn: 0.5520304	total: 1.54s	remaining: 34.2s
43:	learn: 0.5532635	total: 1.6s	remaining: 34.7s
44:	learn: 0.5542491	total: 1.65s	remaining: 35s
45:	learn: 0.5536287	total: 1.7s	remaining: 35.3s
46:	learn: 0.5554433	total: 1.75s	remaining: 35.6s
47:	learn: 0.5557103	total: 1.82s	remaining: 36.1s
48:	learn: 0.5567597	total: 1.86s	remaining: 36.2s
49:	learn: 0.5579871	total: 1.92s	remaining: 36.4s
50:	learn: 0.5568786	total: 1.97s	remaining: 36.7s
51:	learn: 0.5577640	total: 2.02s	remaining: 36.9s
52:	learn: 0.5581255	total: 2.08s	remaining: 37.2s
53:	learn: 0.5584902	total: 2.13s	remaining: 37.4s
54:	learn: 0.5585442	total: 2.19s	remaining: 37.7s
55:	learn: 0.5589707	total: 2.25s	remaining: 37.9s
56:	learn: 0.5599045	total: 2.3s	remaining: 38s
57:	learn: 0.5608067	total: 2.36s	remaining: 38.4s
58:	learn: 0.5603730	total: 2.41s	remaining: 38.5s
59:	learn: 0.5611427	total: 2.47s	remaining: 38.7s
60:	learn: 0.5621917	total: 2.52s	remaining: 38.8s
61:	learn: 0.5622119	total: 2.58s	remaining: 39s
62:	learn: 0.5630643	total: 2.63s	remaining: 39.1s
63:	learn: 0.5636035	total: 2.69s	remaining: 39.3s
64:	learn: 0.5623702	total: 2.75s	remaining: 39.5s
65:	learn: 0.5639166	total: 2.8s	remaining: 39.6s
66:	learn: 0.5643198	total: 2.86s	remaining: 39.8s
67:	learn: 0.5650490	total: 2.92s	remaining: 40s
68:	learn: 0.5644435	total: 2.97s	remaining: 40.1s
69:	learn: 0.5648330	total: 3.02s	remaining: 40.2s
70:	learn: 0.5648771	total: 3.09s	remaining: 40.4s
71:	learn: 0.5657216	total: 3.15s	remaining: 40.6s
72:	learn: 0.5663290	total: 3.2s	remaining: 40.7s
73:	learn: 0.5670567	total: 3.25s	remaining: 40.7s
74:	learn: 0.5658547	total: 3.31s	remaining: 40.8s
75:	learn: 0.5655917	total: 3.36s	remaining: 40.9s
76:	learn: 0.5663581	total: 3.42s	remaining: 41s
77:	learn: 0.5658622	total: 3.47s	remaining: 41.1s
78:	learn: 0.5669918	total: 3.53s	remaining: 41.2s
79:	learn: 0.5668371	total: 3.59s	remaining: 41.3s
80:	learn: 0.5680465	total: 3.64s	remaining: 41.3s
81:	learn: 0.5681166	total: 3.69s	remaining: 41.4s
82:	learn: 0.5678837	total: 3.74s	remaining: 41.4s
83:	learn: 0.5691487	total: 3.8s	remaining: 41.5s
84:	learn: 0.5682065	total: 3.85s	remaining: 41.5s
85:	learn: 0.5688952	total: 3.91s	remaining: 41.5s
86:	learn: 0.5694716	total: 3.96s	remaining: 41.6s
87:	learn: 0.5699817	total: 4.02s	remaining: 41.7s
88:	learn: 0.5692957	total: 4.08s	remaining: 41.8s
89:	learn: 0.5697897	total: 4.13s	remaining: 41.8s
90:	learn: 0.5700411	total: 4.16s	remaining: 41.6s
91:	learn: 0.5701765	total: 4.19s	remaining: 41.4s
92:	learn: 0.5697829	total: 4.22s	remaining: 41.2s
93:	learn: 0.5699675	total: 4.26s	remaining: 41s
94:	learn: 0.5701392	total: 4.29s	remaining: 40.8s
95:	learn: 0.5697699	total: 4.32s	remaining: 40.7s
96:	learn: 0.5705056	total: 4.35s	remaining: 40.5s
97:	learn: 0.5711693	total: 4.38s	remaining: 40.3s
98:	learn: 0.5705966	total: 4.41s	remaining: 40.1s
99:	learn: 0.5703568	total: 4.43s	remaining: 39.9s
100:	learn: 0.5707694	total: 4.47s	remaining: 39.8s
101:	learn: 0.5716524	total: 4.5s	remaining: 39.6s
102:	learn: 0.5721731	total: 4.53s	remaining: 39.4s
103:	learn: 0.5721324	total: 4.56s	remaining: 39.3s
104:	learn: 0.5724298	total: 4.59s	remaining: 39.1s
105:	learn: 0.5726205	total: 4.62s	remaining: 39s
106:	learn: 0.5725828	total: 4.65s	remaining: 38.8s
107:	learn: 0.5727178	total: 4.69s	remaining: 38.7s
108:	learn: 0.5737138	total: 4.72s	remaining: 38.6s
109:	learn: 0.5727299	total: 4.75s	remaining: 38.4s
110:	learn: 0.5735129	total: 4.78s	remaining: 38.3s
111:	learn: 0.5741734	total: 4.81s	remaining: 38.1s
112:	learn: 0.5755443	total: 4.84s	remaining: 38s
113:	learn: 0.5752965	total: 4.87s	remaining: 37.9s
114:	learn: 0.5758468	total: 4.91s	remaining: 37.8s
115:	learn: 0.5761819	total: 4.94s	remaining: 37.6s
116:	learn: 0.5758575	total: 4.97s	remaining: 37.5s
117:	learn: 0.5769159	total: 5.01s	remaining: 37.4s
118:	learn: 0.5773150	total: 5.04s	remaining: 37.3s
119:	learn: 0.5775948	total: 5.07s	remaining: 37.2s
120:	learn: 0.5780272	total: 5.1s	remaining: 37s
121:	learn: 0.5778542	total: 5.13s	remaining: 36.9s
122:	learn: 0.5784430	total: 5.16s	remaining: 36.8s
123:	learn: 0.5791854	total: 5.19s	remaining: 36.7s
124:	learn: 0.5795965	total: 5.22s	remaining: 36.5s
125:	learn: 0.5797684	total: 5.25s	remaining: 36.4s
126:	learn: 0.5793156	total: 5.28s	remaining: 36.3s
127:	learn: 0.5793878	total: 5.31s	remaining: 36.2s
128:	learn: 0.5794964	total: 5.35s	remaining: 36.1s
129:	learn: 0.5802820	total: 5.38s	remaining: 36s
130:	learn: 0.5805806	total: 5.41s	remaining: 35.9s
131:	learn: 0.5806446	total: 5.44s	remaining: 35.8s
132:	learn: 0.5809153	total: 5.47s	remaining: 35.7s
133:	learn: 0.5812131	total: 5.5s	remaining: 35.6s
134:	learn: 0.5819868	total: 5.53s	remaining: 35.4s
135:	learn: 0.5815323	total: 5.56s	remaining: 35.4s
136:	learn: 0.5811086	total: 5.59s	remaining: 35.2s
137:	learn: 0.5815738	total: 5.62s	remaining: 35.1s
138:	learn: 0.5813012	total: 5.65s	remaining: 35s
139:	learn: 0.5818675	total: 5.69s	remaining: 34.9s
140:	learn: 0.5829496	total: 5.71s	remaining: 34.8s
141:	learn: 0.5824360	total: 5.74s	remaining: 34.7s
142:	learn: 0.5828940	total: 5.78s	remaining: 34.6s
143:	learn: 0.5828232	total: 5.81s	remaining: 34.5s
144:	learn: 0.5823366	total: 5.84s	remaining: 34.4s
145:	learn: 0.5830483	total: 5.87s	remaining: 34.3s
146:	learn: 0.5838787	total: 5.9s	remaining: 34.2s
147:	learn: 0.5839605	total: 5.93s	remaining: 34.1s
148:	learn: 0.5832322	total: 5.96s	remaining: 34.1s
149:	learn: 0.5845903	total: 5.99s	remaining: 34s
150:	learn: 0.5842134	total: 6.03s	remaining: 33.9s
151:	learn: 0.5842661	total: 6.07s	remaining: 33.9s
152:	learn: 0.5846434	total: 6.1s	remaining: 33.8s
153:	learn: 0.5853330	total: 6.13s	remaining: 33.7s
154:	learn: 0.5853559	total: 6.16s	remaining: 33.6s
155:	learn: 0.5852431	total: 6.19s	remaining: 33.5s
156:	learn: 0.5855806	total: 6.22s	remaining: 33.4s
157:	learn: 0.5862985	total: 6.25s	remaining: 33.3s
158:	learn: 0.5871430	total: 6.29s	remaining: 33.3s
159:	learn: 0.5865564	total: 6.32s	remaining: 33.2s
160:	learn: 0.5867321	total: 6.35s	remaining: 33.1s
161:	learn: 0.5872771	total: 6.38s	remaining: 33s
162:	learn: 0.5874656	total: 6.41s	remaining: 32.9s
163:	learn: 0.5879563	total: 6.44s	remaining: 32.8s
164:	learn: 0.5881624	total: 6.47s	remaining: 32.8s
165:	learn: 0.5886004	total: 6.5s	remaining: 32.7s
166:	learn: 0.5880333	total: 6.53s	remaining: 32.6s
167:	learn: 0.5880740	total: 6.57s	remaining: 32.5s
168:	learn: 0.5884185	total: 6.6s	remaining: 32.4s
169:	learn: 0.5887095	total: 6.63s	remaining: 32.4s
170:	learn: 0.5890591	total: 6.66s	remaining: 32.3s
171:	learn: 0.5894366	total: 6.7s	remaining: 32.2s
172:	learn: 0.5900283	total: 6.73s	remaining: 32.2s
173:	learn: 0.5896996	total: 6.76s	remaining: 32.1s
174:	learn: 0.5903816	total: 6.79s	remaining: 32s
175:	learn: 0.5905338	total: 6.82s	remaining: 31.9s
176:	learn: 0.5909517	total: 6.85s	remaining: 31.9s
177:	learn: 0.5911421	total: 6.88s	remaining: 31.8s
178:	learn: 0.5915152	total: 6.91s	remaining: 31.7s
179:	learn: 0.5918243	total: 6.94s	remaining: 31.6s
180:	learn: 0.5918923	total: 6.97s	remaining: 31.5s
181:	learn: 0.5922066	total: 7s	remaining: 31.5s
182:	learn: 0.5919843	total: 7.03s	remaining: 31.4s
183:	learn: 0.5925965	total: 7.07s	remaining: 31.4s
184:	learn: 0.5925219	total: 7.11s	remaining: 31.3s
185:	learn: 0.5924413	total: 7.14s	remaining: 31.3s
186:	learn: 0.5927904	total: 7.17s	remaining: 31.2s
187:	learn: 0.5934594	total: 7.2s	remaining: 31.1s
188:	learn: 0.5942023	total: 7.23s	remaining: 31s
189:	learn: 0.5938281	total: 7.26s	remaining: 30.9s
190:	learn: 0.5938706	total: 7.29s	remaining: 30.9s
191:	learn: 0.5940862	total: 7.32s	remaining: 30.8s
192:	learn: 0.5942568	total: 7.35s	remaining: 30.8s
193:	learn: 0.5946772	total: 7.38s	remaining: 30.7s
194:	learn: 0.5946347	total: 7.42s	remaining: 30.6s
195:	learn: 0.5951611	total: 7.45s	remaining: 30.5s
196:	learn: 0.5954713	total: 7.48s	remaining: 30.5s
197:	learn: 0.5961029	total: 7.51s	remaining: 30.4s
198:	learn: 0.5966383	total: 7.54s	remaining: 30.4s
199:	learn: 0.5957950	total: 7.57s	remaining: 30.3s
200:	learn: 0.5961820	total: 7.61s	remaining: 30.2s
201:	learn: 0.5965683	total: 7.64s	remaining: 30.2s
202:	learn: 0.5968542	total: 7.67s	remaining: 30.1s
203:	learn: 0.5968158	total: 7.7s	remaining: 30s
204:	learn: 0.5967121	total: 7.73s	remaining: 30s
205:	learn: 0.5966409	total: 7.76s	remaining: 29.9s
206:	learn: 0.5969970	total: 7.79s	remaining: 29.9s
207:	learn: 0.5980106	total: 7.83s	remaining: 29.8s
208:	learn: 0.5978002	total: 7.86s	remaining: 29.7s
209:	learn: 0.5982158	total: 7.88s	remaining: 29.7s
210:	learn: 0.5984850	total: 7.92s	remaining: 29.6s
211:	learn: 0.5993539	total: 7.95s	remaining: 29.6s
212:	learn: 0.5997654	total: 7.98s	remaining: 29.5s
213:	learn: 0.5997988	total: 8.01s	remaining: 29.4s
214:	learn: 0.6000582	total: 8.04s	remaining: 29.3s
215:	learn: 0.5998958	total: 8.06s	remaining: 29.3s
216:	learn: 0.5998517	total: 8.1s	remaining: 29.2s
217:	learn: 0.5997845	total: 8.14s	remaining: 29.2s
218:	learn: 0.6000265	total: 8.17s	remaining: 29.2s
219:	learn: 0.6002243	total: 8.2s	remaining: 29.1s
220:	learn: 0.5999965	total: 8.23s	remaining: 29s
221:	learn: 0.5994679	total: 8.26s	remaining: 29s
222:	learn: 0.5990895	total: 8.3s	remaining: 28.9s
223:	learn: 0.5989460	total: 8.33s	remaining: 28.9s
224:	learn: 0.5992010	total: 8.36s	remaining: 28.8s
225:	learn: 0.5995138	total: 8.39s	remaining: 28.7s
226:	learn: 0.5996430	total: 8.42s	remaining: 28.7s
227:	learn: 0.6002668	total: 8.45s	remaining: 28.6s
228:	learn: 0.6000106	total: 8.48s	remaining: 28.5s
229:	learn: 0.6004278	total: 8.51s	remaining: 28.5s
230:	learn: 0.6010089	total: 8.54s	remaining: 28.4s
231:	learn: 0.6011924	total: 8.57s	remaining: 28.4s
232:	learn: 0.6015954	total: 8.6s	remaining: 28.3s
233:	learn: 0.6019249	total: 8.63s	remaining: 28.2s
234:	learn: 0.6018913	total: 8.66s	remaining: 28.2s
235:	learn: 0.6014165	total: 8.69s	remaining: 28.1s
236:	learn: 0.6017090	total: 8.72s	remaining: 28.1s
237:	learn: 0.6024745	total: 8.75s	remaining: 28s
238:	learn: 0.6025661	total: 8.79s	remaining: 28s
239:	learn: 0.6020890	total: 8.82s	remaining: 27.9s
240:	learn: 0.6015599	total: 8.85s	remaining: 27.9s
241:	learn: 0.6021600	total: 8.88s	remaining: 27.8s
242:	learn: 0.6019484	total: 8.91s	remaining: 27.8s
243:	learn: 0.6025510	total: 8.94s	remaining: 27.7s
244:	learn: 0.6015747	total: 8.97s	remaining: 27.6s
245:	learn: 0.6016059	total: 9s	remaining: 27.6s
246:	learn: 0.6014064	total: 9.03s	remaining: 27.5s
247:	learn: 0.6014959	total: 9.06s	remaining: 27.5s
248:	learn: 0.6015206	total: 9.09s	remaining: 27.4s
249:	learn: 0.6022372	total: 9.12s	remaining: 27.4s
250:	learn: 0.6022197	total: 9.15s	remaining: 27.3s
251:	learn: 0.6026780	total: 9.2s	remaining: 27.3s
252:	learn: 0.6028698	total: 9.22s	remaining: 27.2s
253:	learn: 0.6026905	total: 9.26s	remaining: 27.2s
254:	learn: 0.6032397	total: 9.29s	remaining: 27.1s
255:	learn: 0.6034762	total: 9.32s	remaining: 27.1s
256:	learn: 0.6041239	total: 9.35s	remaining: 27s
257:	learn: 0.6039041	total: 9.38s	remaining: 27s
258:	learn: 0.6039608	total: 9.41s	remaining: 26.9s
259:	learn: 0.6033151	total: 9.44s	remaining: 26.9s
260:	learn: 0.6035410	total: 9.47s	remaining: 26.8s
261:	learn: 0.6042935	total: 9.51s	remaining: 26.8s
262:	learn: 0.6032600	total: 9.54s	remaining: 26.7s
263:	learn: 0.6040158	total: 9.56s	remaining: 26.7s
264:	learn: 0.6046688	total: 9.6s	remaining: 26.6s
265:	learn: 0.6041704	total: 9.63s	remaining: 26.6s
266:	learn: 0.6049967	total: 9.66s	remaining: 26.5s
267:	learn: 0.6048778	total: 9.69s	remaining: 26.5s
268:	learn: 0.6055153	total: 9.72s	remaining: 26.4s
269:	learn: 0.6060702	total: 9.76s	remaining: 26.4s
270:	learn: 0.6064387	total: 9.79s	remaining: 26.3s
271:	learn: 0.6067263	total: 9.82s	remaining: 26.3s
272:	learn: 0.6069139	total: 9.85s	remaining: 26.2s
273:	learn: 0.6070788	total: 9.88s	remaining: 26.2s
274:	learn: 0.6078031	total: 9.91s	remaining: 26.1s
275:	learn: 0.6077092	total: 9.94s	remaining: 26.1s
276:	learn: 0.6078362	total: 9.97s	remaining: 26s
277:	learn: 0.6078334	total: 10s	remaining: 26s
278:	learn: 0.6083202	total: 10s	remaining: 25.9s
279:	learn: 0.6085943	total: 10.1s	remaining: 25.9s
280:	learn: 0.6082179	total: 10.1s	remaining: 25.8s
281:	learn: 0.6084244	total: 10.1s	remaining: 25.8s
282:	learn: 0.6085519	total: 10.2s	remaining: 25.7s
283:	learn: 0.6087533	total: 10.2s	remaining: 25.7s
284:	learn: 0.6088309	total: 10.2s	remaining: 25.7s
285:	learn: 0.6087725	total: 10.3s	remaining: 25.6s
286:	learn: 0.6083059	total: 10.3s	remaining: 25.6s
287:	learn: 0.6095481	total: 10.3s	remaining: 25.5s
288:	learn: 0.6091884	total: 10.4s	remaining: 25.5s
289:	learn: 0.6087157	total: 10.4s	remaining: 25.5s
290:	learn: 0.6089588	total: 10.4s	remaining: 25.4s
291:	learn: 0.6090087	total: 10.5s	remaining: 25.4s
292:	learn: 0.6094893	total: 10.5s	remaining: 25.3s
293:	learn: 0.6098072	total: 10.5s	remaining: 25.3s
294:	learn: 0.6107774	total: 10.6s	remaining: 25.2s
295:	learn: 0.6106456	total: 10.6s	remaining: 25.2s
296:	learn: 0.6107349	total: 10.6s	remaining: 25.1s
297:	learn: 0.6101077	total: 10.6s	remaining: 25.1s
298:	learn: 0.6107043	total: 10.7s	remaining: 25s
299:	learn: 0.6112530	total: 10.7s	remaining: 25s
300:	learn: 0.6116106	total: 10.7s	remaining: 24.9s
301:	learn: 0.6117298	total: 10.8s	remaining: 24.9s
302:	learn: 0.6118626	total: 10.8s	remaining: 24.9s
303:	learn: 0.6125351	total: 10.8s	remaining: 24.8s
304:	learn: 0.6122258	total: 10.9s	remaining: 24.8s
305:	learn: 0.6123902	total: 10.9s	remaining: 24.7s
306:	learn: 0.6129474	total: 10.9s	remaining: 24.7s
307:	learn: 0.6122005	total: 11s	remaining: 24.6s
308:	learn: 0.6122503	total: 11s	remaining: 24.6s
309:	learn: 0.6122813	total: 11s	remaining: 24.5s
310:	learn: 0.6128639	total: 11s	remaining: 24.5s
311:	learn: 0.6123653	total: 11.1s	remaining: 24.4s
312:	learn: 0.6124385	total: 11.1s	remaining: 24.4s
313:	learn: 0.6133100	total: 11.1s	remaining: 24.3s
314:	learn: 0.6138991	total: 11.2s	remaining: 24.3s
315:	learn: 0.6134271	total: 11.2s	remaining: 24.2s
316:	learn: 0.6140758	total: 11.2s	remaining: 24.2s
317:	learn: 0.6131736	total: 11.3s	remaining: 24.2s
318:	learn: 0.6140115	total: 11.3s	remaining: 24.1s
319:	learn: 0.6139925	total: 11.3s	remaining: 24.1s
320:	learn: 0.6143956	total: 11.4s	remaining: 24.1s
321:	learn: 0.6142827	total: 11.4s	remaining: 24s
322:	learn: 0.6142145	total: 11.4s	remaining: 24s
323:	learn: 0.6144535	total: 11.5s	remaining: 23.9s
324:	learn: 0.6146261	total: 11.5s	remaining: 23.9s
325:	learn: 0.6141479	total: 11.5s	remaining: 23.8s
326:	learn: 0.6140566	total: 11.6s	remaining: 23.8s
327:	learn: 0.6148238	total: 11.6s	remaining: 23.7s
328:	learn: 0.6148386	total: 11.6s	remaining: 23.7s
329:	learn: 0.6146714	total: 11.6s	remaining: 23.6s
330:	learn: 0.6145407	total: 11.7s	remaining: 23.6s
331:	learn: 0.6150407	total: 11.7s	remaining: 23.6s
332:	learn: 0.6150992	total: 11.7s	remaining: 23.5s
333:	learn: 0.6148872	total: 11.8s	remaining: 23.5s
334:	learn: 0.6153710	total: 11.8s	remaining: 23.4s
335:	learn: 0.6156237	total: 11.8s	remaining: 23.4s
336:	learn: 0.6156809	total: 11.9s	remaining: 23.3s
337:	learn: 0.6156700	total: 11.9s	remaining: 23.3s
338:	learn: 0.6155763	total: 11.9s	remaining: 23.2s
339:	learn: 0.6156293	total: 11.9s	remaining: 23.2s
340:	learn: 0.6161013	total: 12s	remaining: 23.2s
341:	learn: 0.6162947	total: 12s	remaining: 23.1s
342:	learn: 0.6166743	total: 12s	remaining: 23.1s
343:	learn: 0.6171377	total: 12.1s	remaining: 23s
344:	learn: 0.6170049	total: 12.1s	remaining: 23s
345:	learn: 0.6173104	total: 12.1s	remaining: 22.9s
346:	learn: 0.6176312	total: 12.2s	remaining: 22.9s
347:	learn: 0.6178678	total: 12.2s	remaining: 22.8s
348:	learn: 0.6177716	total: 12.2s	remaining: 22.8s
349:	learn: 0.6178186	total: 12.2s	remaining: 22.7s
350:	learn: 0.6176034	total: 12.3s	remaining: 22.7s
351:	learn: 0.6173351	total: 12.3s	remaining: 22.7s
352:	learn: 0.6169657	total: 12.4s	remaining: 22.6s
353:	learn: 0.6173607	total: 12.4s	remaining: 22.6s
354:	learn: 0.6172464	total: 12.4s	remaining: 22.6s
355:	learn: 0.6170640	total: 12.4s	remaining: 22.5s
356:	learn: 0.6176320	total: 12.5s	remaining: 22.5s
357:	learn: 0.6179019	total: 12.5s	remaining: 22.4s
358:	learn: 0.6190169	total: 12.5s	remaining: 22.4s
359:	learn: 0.6190919	total: 12.6s	remaining: 22.4s
360:	learn: 0.6190228	total: 12.6s	remaining: 22.3s
361:	learn: 0.6194338	total: 12.6s	remaining: 22.3s
362:	learn: 0.6195945	total: 12.7s	remaining: 22.2s
363:	learn: 0.6195681	total: 12.7s	remaining: 22.2s
364:	learn: 0.6199745	total: 12.7s	remaining: 22.1s
365:	learn: 0.6197300	total: 12.8s	remaining: 22.1s
366:	learn: 0.6203120	total: 12.8s	remaining: 22.1s
367:	learn: 0.6204514	total: 12.8s	remaining: 22s
368:	learn: 0.6198323	total: 12.8s	remaining: 22s
369:	learn: 0.6201834	total: 12.9s	remaining: 21.9s
370:	learn: 0.6209972	total: 12.9s	remaining: 21.9s
371:	learn: 0.6204892	total: 12.9s	remaining: 21.8s
372:	learn: 0.6210909	total: 13s	remaining: 21.8s
373:	learn: 0.6211862	total: 13s	remaining: 21.8s
374:	learn: 0.6217770	total: 13s	remaining: 21.7s
375:	learn: 0.6214498	total: 13.1s	remaining: 21.7s
376:	learn: 0.6215030	total: 13.1s	remaining: 21.6s
377:	learn: 0.6218094	total: 13.1s	remaining: 21.6s
378:	learn: 0.6217190	total: 13.1s	remaining: 21.5s
379:	learn: 0.6220342	total: 13.2s	remaining: 21.5s
380:	learn: 0.6219035	total: 13.2s	remaining: 21.5s
381:	learn: 0.6221433	total: 13.2s	remaining: 21.4s
382:	learn: 0.6219263	total: 13.3s	remaining: 21.4s
383:	learn: 0.6219962	total: 13.3s	remaining: 21.3s
384:	learn: 0.6224611	total: 13.3s	remaining: 21.3s
385:	learn: 0.6221952	total: 13.4s	remaining: 21.3s
386:	learn: 0.6223093	total: 13.4s	remaining: 21.3s
387:	learn: 0.6221869	total: 13.5s	remaining: 21.2s
388:	learn: 0.6221944	total: 13.5s	remaining: 21.2s

CatBoostClassifier(depth=5, eval_metric='F1', iterations=1000, learning_rate=0.03, loss_function='Logloss', random_state=42)

In [43]:
# ============================================================
# FEATURE IMPORTANCE
# ============================================================

feature_importance = pd.DataFrame({
    'Feature': x_train_over.columns,
    'Importance': cat_model.get_feature_importance()
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

                Feature  Importance
20         water_intake    6.020082
17         sugar_intake    5.870700
13           work_hours    5.781293
9               glucose    5.665964
21          screen_time    5.411029
11          sleep_hours    5.403102
5            waist_size    5.398931
8           cholesterol    5.269271
15          daily_steps    5.124527
7            heart_rate    4.883786
6        blood_pressure    4.692173
16       calorie_intake    4.664156
3                weight    4.579931
10              insulin    4.512386
2                height    4.351468
0                   age    4.261818
4                   bmi    4.109970
14    physical_activity    3.986165
22         stress_level    1.582425
26        meals_per_day    1.310995
12        sleep_quality    1.238534
23            diet_type    1.215442
24        exercise_type    1.071343
27      caffeine_intake    0.896187
19        smoking_level    0.860107
18  alcohol_consumption    0.747448
25         device_usage    0.580246
1                gender    0.510521

Tes Data

In [44]:


y_prob = cat_model.predict_proba(x_test)[:,1]

threshold = 0.5

y_pred = (y_prob > threshold).astype(int)


# Evaluasi
cat_acc = accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))

print('Akurasi CatBoost = {:.2f}%'.format(cat_acc*100))

              precision    recall  f1-score   support

           0       0.70      0.58      0.64     14019
           1       0.30      0.42      0.35      5981

    accuracy                           0.53     20000
   macro avg       0.50      0.50      0.49     20000
weighted avg       0.58      0.53      0.55     20000

Akurasi CatBoost = 53.47%

# note 29 mei 2026
# - cari metode duplikat yang lain
# - coba imbalance data dengan oversampling di kodingan yang sekarang
# - gunakan loss function yang lain