1. Data Understanding

In [224]:
#install library kaggle untuk mengakses dataset dari Kaggle
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [225]:
import kagglehub
# Download latest version
path = kagglehub.dataset_download("mahdimashayekhi/disease-risk-from-daily-habits")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'disease-risk-from-daily-habits' dataset.
Path to dataset files: /kaggle/input/disease-risk-from-daily-habits

In [226]:
#install library catboost untuk model machine learning
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [227]:
# Import library yang dibutuhkan
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.model_selection import GridSearchCV

In [228]:
# mengecek file yang telah di download
print(os.listdir(path))

['health_lifestyle_classification.csv']

In [229]:
# Membaca dataset
df = pd.read_csv(path + "/health_lifestyle_classification.csv")
df.head()

   survey_code  age  gender      height     weight        bmi  bmi_estimated  bmi_scaled  bmi_corrected  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level  mental_health_score mental_health_support education_level    job_type occupation       income   diet_type exercise_type device_usage healthcare_access insurance sunlight_exposure  meals_per_day caffeine_intake family_history pet_owner  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage   target
0            1   56    Male  173.416872  56.886640  18.915925      18.915925   56.747776      18.989117   72.165130      118.264254   60.749825   214.580523  103.008176        NaN     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887                 NaN    Non-smoker      1.694262     5.003963             2                    8                    No             PhD        Tech     Farmer  6759.821719       Vegan      Strength         High              Poor        No              High              5        Moderate             No       Yes                  0               1.0                       5.5                -2.275502  healthy
1            2   69  Female  163.207380  97.799859  36.716278      36.716278  110.148833      36.511417   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3                    9                    No     High School      Office   Engineer  6240.517690       Vegan        Cardio     Moderate          Moderate        No              High              5            High            Yes        No                  0               1.0                       5.5                 6.239340  healthy
2            3   46    Male  177.281966  80.687562  25.673050      25.673050   77.019151      25.587429   90.295030      123.073698   76.043212   138.134787   89.180302        NaN     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0                    1                    No          Master      Office    Teacher  3429.179266       Vegan        Cardio         High              Good       Yes              High              4        Moderate             No        No                  0               1.0                       5.5                 5.423737  healthy
3            4   32  Female  172.101255  63.142868  21.318480      21.318480   63.955440      21.177109  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10                    4                    No          Master       Labor    Teacher  2618.503534  Vegetarian         Mixed          Low          Moderate        No              High              1             NaN             No       Yes                  0               1.0                       5.5                 8.388611  healthy
4            5   60  Female  163.608816  40.000000  14.943302      14.943302   44.829907      14.844299   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322                 NaN         Heavy      1.968393     3.180087             9                    7                   Yes          Master  Unemployed     Doctor  3662.086276       Vegan           NaN          Low          Moderate       Yes              High              1            High            Yes       Yes                  0               1.0                       5.5                 0.332622  healthy

In [230]:
# mengecek jumlah baris dan kolom pada dataset
print("data shape : ", df.shape)

data shape :  (100000, 48)

In [231]:
# Mengecek informasi dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            92331 non-null   float64
 11  heart_rate                85997 non-null   float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   84164 non-null   float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               91671 non-null   float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       57613 non-null   object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    91530 non-null   float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             75031 non-null   object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           66739 non-null   object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          89526 non-null   float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB

In [232]:
# describe dataset untuk melihat statistik dasar dari dataset
df.describe()

         survey_code            age         height         weight            bmi  bmi_estimated     bmi_scaled  bmi_corrected     waist_size  blood_pressure    heart_rate    cholesterol        glucose       insulin    sleep_hours     work_hours  physical_activity   daily_steps  calorie_intake   sugar_intake   water_intake    screen_time   stress_level  mental_health_score        income  meals_per_day  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage
count  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000    92331.000000  85997.000000  100000.000000  100000.000000  84164.000000  100000.000000  100000.000000      100000.000000  91671.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000        100000.000000  91530.000000  100000.000000           100000.0           89526.0                  100000.0            100000.000000
mean    50000.500000      48.525990     170.023707      70.064862      24.493876      24.493876      73.481627      24.494140      84.933043      119.980149     74.969177     189.966438      99.994538     14.988258       7.002008       8.001331           3.038344   7012.925748     2201.428579      60.047165       2.006373       6.021525       4.991600             5.004680   4038.127284       2.998720                0.0               1.0                       5.5                 0.015726
std     28867.657797      17.886768       9.982798      14.693667       5.951069       5.951069      17.853206       5.954184      12.040314       15.015503      9.941668      29.981934      19.982828      5.002783       1.496821       1.994723           1.884475   2488.989356      400.516318      19.966850       0.688868       2.933835       3.154997             3.164228   1930.025678       1.414786                0.0               0.0                       0.0                 5.764489
min         1.000000      18.000000     140.000000      40.000000       9.988495       9.988495      29.965484       9.893845      34.093185       59.128168     34.745092      58.410902      12.434931     -6.794483       3.000000       0.000000           0.000000   1000.000000      527.172360     -27.882444       0.500000       0.000000       0.000000             0.000000    500.000000       1.000000                0.0               1.0                       5.5                -9.999895
25%     25000.750000      33.000000     163.306615      59.856938      20.271405      20.271405      60.814215      20.271059      76.795185      109.812060     68.275432     169.667738      86.461401     11.627114       5.986781       6.651093           1.633799   5320.858377     1932.278165      46.504292       1.532011       3.971318       2.000000             2.000000   2665.402843       2.000000                0.0               1.0                       5.5                -4.980501
50%     50000.500000      48.000000     170.016778      69.924141      24.156734      24.156734      72.470201      24.151699      84.957139      119.951794     75.046211     190.044579      99.986834     14.983414       6.998164       8.004549           2.971222   7004.285450     2200.992765      60.047905       2.000659       5.991171       5.000000             5.000000   4004.601345       3.000000                0.0               1.0                       5.5                 0.015589
75%     75000.250000      64.000000     176.728920      80.027418      28.258696      28.258696      84.776088      28.247648      93.018713      130.120621     81.685914     210.222005     113.508722     18.361928       8.019219       9.353669           4.326500   8702.281300     2471.218160      73.476386       2.473047       8.024470       8.000000             8.000000   5360.012694       4.000000                0.0               1.0                       5.5                 5.008424
max    100000.000000      79.000000     210.000000     139.250894      59.234792      59.234792     177.704377      59.142646     133.153631      184.439195    114.136041     319.875613     183.883548     35.464749      12.000000      16.000000          11.631898  18064.969543     3949.019017     141.514522       5.000000      16.000000      10.000000            10.000000  12029.409353       5.000000                0.0               1.0                       5.5                 9.999966

2. Cleaning Data

# missing value

In [233]:
# Mengecek nilai yang hilang
missing_values = df.isnull().sum()

print("missing value per kolom : ")
print(missing_values[missing_values>0])

missing value per kolom :
blood_pressure          7669
heart_rate             14003
insulin                15836
daily_steps             8329
alcohol_consumption    42387
income                  8470
exercise_type          24969
caffeine_intake        33261
gene_marker_flag       10474
dtype: int64

In [234]:
# Mengecek persentase nilai yang hilang
missing_percentage = df.isnull().mean().sort_values(ascending=False)*100
print("percentage of missing values per column : ")
print(missing_percentage[missing_percentage>0])

percentage of missing values per column :
alcohol_consumption    42.387
caffeine_intake        33.261
exercise_type          24.969
insulin                15.836
heart_rate             14.003
gene_marker_flag       10.474
income                  8.470
daily_steps             8.329
blood_pressure          7.669
dtype: float64

In [235]:
# Mengecek jumlah nilai yang hilang per kolom
print("Jumlah Missing Value tiap kolom:\n")

print(df.isna().sum())

Jumlah Missing Value tiap kolom:

survey_code                     0
age                             0
gender                          0
height                          0
weight                          0
bmi                             0
bmi_estimated                   0
bmi_scaled                      0
bmi_corrected                   0
waist_size                      0
blood_pressure               7669
heart_rate                  14003
cholesterol                     0
glucose                         0
insulin                     15836
sleep_hours                     0
sleep_quality                   0
work_hours                      0
physical_activity               0
daily_steps                  8329
calorie_intake                  0
sugar_intake                    0
alcohol_consumption         42387
smoking_level                   0
water_intake                    0
screen_time                     0
stress_level                    0
mental_health_score             0
mental_health_support           0
education_level                 0
job_type                        0
occupation                      0
income                       8470
diet_type                       0
exercise_type               24969
device_usage                    0
healthcare_access               0
insurance                       0
sunlight_exposure               0
meals_per_day                   0
caffeine_intake             33261
family_history                  0
pet_owner                       0
electrolyte_level               0
gene_marker_flag            10474
environmental_risk_score        0
daily_supplement_dosage         0
target                          0
dtype: int64

In [236]:
# Mengecek jumlah nilai yang hilang secara keseluruhan dataset
df.isna().sum().sum()

np.int64(165398)

In [237]:
# Mengisi nilai yang hilang dengan median untuk kolom numerik dan modus untuk kolom kategorikal

# 1) Kolom numerik
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    df[col] = df[col].fillna(
        df[col].median()
    )

# 2) Kolom kategorikal
cat_cols = df.select_dtypes(
    include='object'
).columns

for col in cat_cols:
    df[col] = df[col].fillna(
        "Unknown"
    )

In [238]:
(df.isna().sum()/len(df))*100

survey_code                 0.0
age                         0.0
gender                      0.0
height                      0.0
weight                      0.0
bmi                         0.0
bmi_estimated               0.0
bmi_scaled                  0.0
bmi_corrected               0.0
waist_size                  0.0
blood_pressure              0.0
heart_rate                  0.0
cholesterol                 0.0
glucose                     0.0
insulin                     0.0
sleep_hours                 0.0
sleep_quality               0.0
work_hours                  0.0
physical_activity           0.0
daily_steps                 0.0
calorie_intake              0.0
sugar_intake                0.0
alcohol_consumption         0.0
smoking_level               0.0
water_intake                0.0
screen_time                 0.0
stress_level                0.0
mental_health_score         0.0
mental_health_support       0.0
education_level             0.0
job_type                    0.0
occupation                  0.0
income                      0.0
diet_type                   0.0
exercise_type               0.0
device_usage                0.0
healthcare_access           0.0
insurance                   0.0
sunlight_exposure           0.0
meals_per_day               0.0
caffeine_intake             0.0
family_history              0.0
pet_owner                   0.0
electrolyte_level           0.0
gene_marker_flag            0.0
environmental_risk_score    0.0
daily_supplement_dosage     0.0
target                      0.0
dtype: float64

In [239]:
df.isna().sum().sum()

np.int64(0)

In [240]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   survey_code               100000 non-null  int64
 1   age                       100000 non-null  int64
 2   gender                    100000 non-null  object
 3   height                    100000 non-null  float64
 4   weight                    100000 non-null  float64
 5   bmi                       100000 non-null  float64
 6   bmi_estimated             100000 non-null  float64
 7   bmi_scaled                100000 non-null  float64
 8   bmi_corrected             100000 non-null  float64
 9   waist_size                100000 non-null  float64
 10  blood_pressure            100000 non-null  float64
 11  heart_rate                100000 non-null  float64
 12  cholesterol               100000 non-null  float64
 13  glucose                   100000 non-null  float64
 14  insulin                   100000 non-null  float64
 15  sleep_hours               100000 non-null  float64
 16  sleep_quality             100000 non-null  object
 17  work_hours                100000 non-null  float64
 18  physical_activity         100000 non-null  float64
 19  daily_steps               100000 non-null  float64
 20  calorie_intake            100000 non-null  float64
 21  sugar_intake              100000 non-null  float64
 22  alcohol_consumption       100000 non-null  object
 23  smoking_level             100000 non-null  object
 24  water_intake              100000 non-null  float64
 25  screen_time               100000 non-null  float64
 26  stress_level              100000 non-null  int64
 27  mental_health_score       100000 non-null  int64
 28  mental_health_support     100000 non-null  object
 29  education_level           100000 non-null  object
 30  job_type                  100000 non-null  object
 31  occupation                100000 non-null  object
 32  income                    100000 non-null  float64
 33  diet_type                 100000 non-null  object
 34  exercise_type             100000 non-null  object
 35  device_usage              100000 non-null  object
 36  healthcare_access         100000 non-null  object
 37  insurance                 100000 non-null  object
 38  sunlight_exposure         100000 non-null  object
 39  meals_per_day             100000 non-null  int64
 40  caffeine_intake           100000 non-null  object
 41  family_history            100000 non-null  object
 42  pet_owner                 100000 non-null  object
 43  electrolyte_level         100000 non-null  int64
 44  gene_marker_flag          100000 non-null  float64
 45  environmental_risk_score  100000 non-null  float64
 46  daily_supplement_dosage   100000 non-null  float64
 47  target                    100000 non-null  object
dtypes: float64(24), int64(6), object(18)
memory usage: 36.6+ MB
None

# cek duplikat

In [241]:
# Mengecek duplikasi data
df.duplicated().sum()

np.int64(0)

In [242]:
df[df.duplicated()]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

In [243]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

In [244]:
# ============================================================
# CEK DUPLICATE DATA
# ============================================================

# Total duplicate
total_duplicate = df.duplicated().sum()

print("Total Duplicate:", total_duplicate)

# Persentase duplicate
duplicate_percent = (
    total_duplicate / len(df)
) * 100

print(
    "Persentase Duplicate:",
    round(duplicate_percent, 2),
    "%"
)

# ============================================================
# TAMPILKAN DATA DUPLICATE
# ============================================================

duplicate_rows = df[
    df.duplicated(keep=False)
]

print("\nData Duplicate:\n")

print(duplicate_rows)

# ============================================================
# JUMLAH ROW DUPLICATE
# ============================================================

print(
    "\nJumlah Row Duplicate:",
    duplicate_rows.shape[0]
)

Total Duplicate: 0
Persentase Duplicate: 0.0 %

Data Duplicate:

Empty DataFrame
Columns: [survey_code, age, gender, height, weight, bmi, bmi_estimated, bmi_scaled, bmi_corrected, waist_size, blood_pressure, heart_rate, cholesterol, glucose, insulin, sleep_hours, sleep_quality, work_hours, physical_activity, daily_steps, calorie_intake, sugar_intake, alcohol_consumption, smoking_level, water_intake, screen_time, stress_level, mental_health_score, mental_health_support, education_level, job_type, occupation, income, diet_type, exercise_type, device_usage, healthcare_access, insurance, sunlight_exposure, meals_per_day, caffeine_intake, family_history, pet_owner, electrolyte_level, gene_marker_flag, environmental_risk_score, daily_supplement_dosage, target]
Index: []

Jumlah Row Duplicate: 0

In [245]:
df.head()

   survey_code  age  gender      height     weight        bmi  bmi_estimated  bmi_scaled  bmi_corrected  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level  mental_health_score mental_health_support education_level    job_type occupation       income   diet_type exercise_type device_usage healthcare_access insurance sunlight_exposure  meals_per_day caffeine_intake family_history pet_owner  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage   target
0            1   56    Male  173.416872  56.886640  18.915925      18.915925   56.747776      18.989117   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887             Unknown    Non-smoker      1.694262     5.003963             2                    8                    No             PhD        Tech     Farmer  6759.821719       Vegan      Strength         High              Poor        No              High              5        Moderate             No       Yes                  0               1.0                       5.5                -2.275502  healthy
1            2   69  Female  163.207380  97.799859  36.716278      36.716278  110.148833      36.511417   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3                    9                    No     High School      Office   Engineer  6240.517690       Vegan        Cardio     Moderate          Moderate        No              High              5            High            Yes        No                  0               1.0                       5.5                 6.239340  healthy
2            3   46    Male  177.281966  80.687562  25.673050      25.673050   77.019151      25.587429   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0                    1                    No          Master      Office    Teacher  3429.179266       Vegan        Cardio         High              Good       Yes              High              4        Moderate             No        No                  0               1.0                       5.5                 5.423737  healthy
3            4   32  Female  172.101255  63.142868  21.318480      21.318480   63.955440      21.177109  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10                    4                    No          Master       Labor    Teacher  2618.503534  Vegetarian         Mixed          Low          Moderate        No              High              1         Unknown             No       Yes                  0               1.0                       5.5                 8.388611  healthy
4            5   60  Female  163.608816  40.000000  14.943302      14.943302   44.829907      14.844299   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322             Unknown         Heavy      1.968393     3.180087             9                    7                   Yes          Master  Unemployed     Doctor  3662.086276       Vegan       Unknown          Low          Moderate       Yes              High              1            High            Yes       Yes                  0               1.0                       5.5                 0.332622  healthy

3. Cek Tipe Data

In [246]:
# Mengecek tipe data setiap kolom
print(df.dtypes)

survey_code                   int64
age                           int64
gender                       object
height                      float64
weight                      float64
bmi                         float64
bmi_estimated               float64
bmi_scaled                  float64
bmi_corrected               float64
waist_size                  float64
blood_pressure              float64
heart_rate                  float64
cholesterol                 float64
glucose                     float64
insulin                     float64
sleep_hours                 float64
sleep_quality                object
work_hours                  float64
physical_activity           float64
daily_steps                 float64
calorie_intake              float64
sugar_intake                float64
alcohol_consumption          object
smoking_level                object
water_intake                float64
screen_time                 float64
stress_level                  int64
mental_health_score           int64
mental_health_support        object
education_level              object
job_type                     object
occupation                   object
income                      float64
diet_type                    object
exercise_type                object
device_usage                 object
healthcare_access            object
insurance                    object
sunlight_exposure            object
meals_per_day                 int64
caffeine_intake              object
family_history               object
pet_owner                    object
electrolyte_level             int64
gene_marker_flag            float64
environmental_risk_score    float64
daily_supplement_dosage     float64
target                       object
dtype: object

In [247]:
# Mengecek nilai unik pada setiap kolom kategorikal
for col in df.select_dtypes(include='object'):

    print(f"\n===== {col} =====")

    print(df[col].unique())

===== gender =====
['Male' 'Female']

===== sleep_quality =====
['Fair' 'Good' 'Poor' 'Excellent']

===== alcohol_consumption =====
['Unknown' 'Regularly' 'Occasionally']

===== smoking_level =====
['Non-smoker' 'Light' 'Heavy']

===== mental_health_support =====
['No' 'Yes']

===== education_level =====
['PhD' 'High School' 'Master' 'Bachelor']

===== job_type =====
['Tech' 'Office' 'Labor' 'Unemployed' 'Service' 'Healthcare']

===== occupation =====
['Farmer' 'Engineer' 'Teacher' 'Doctor' 'Driver' 'Artist']

===== diet_type =====
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']

===== exercise_type =====
['Strength' 'Cardio' 'Mixed' 'Unknown']

===== device_usage =====
['High' 'Moderate' 'Low']

===== healthcare_access =====
['Poor' 'Moderate' 'Good']

===== insurance =====
['No' 'Yes']

===== sunlight_exposure =====
['High' 'Low' 'Moderate']

===== caffeine_intake =====
['Moderate' 'High' 'Unknown']

===== family_history =====
['No' 'Yes']

===== pet_owner =====
['Yes' 'No']

===== target =====
['healthy' 'diseased']

In [248]:
# mengecek semua isi tabel untuk memastikan tidak ada nilai yang aneh atau tidak konsisten

# Tampilkan semua kolom
pd.set_option('display.max_columns', None)

# Lebar tampilan terminal
pd.set_option('display.width', 1000)

# Panjang isi kolom tidak dipotong
pd.set_option('display.max_colwidth', None)

# Tampilkan semua baris jika diperlukan
pd.set_option('display.max_rows', None)

In [249]:
df.head()

   survey_code  age  gender      height     weight        bmi  bmi_estimated  bmi_scaled  bmi_corrected  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake alcohol_consumption smoking_level  water_intake  screen_time  stress_level  mental_health_score mental_health_support education_level    job_type occupation       income   diet_type exercise_type device_usage healthcare_access insurance sunlight_exposure  meals_per_day caffeine_intake family_history pet_owner  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage   target
0            1   56    Male  173.416872  56.886640  18.915925      18.915925   56.747776      18.989117   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885          Fair    7.671313           0.356918  13320.942595     2673.546960     44.476887             Unknown    Non-smoker      1.694262     5.003963             2                    8                    No             PhD        Tech     Farmer  6759.821719       Vegan      Strength         High              Poor        No              High              5        Moderate             No       Yes                  0               1.0                       5.5                -2.275502  healthy
1            2   69  Female  163.207380  97.799859  36.716278      36.716278  110.148833      36.511417   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410          Good    9.515198           0.568219  11911.201401     2650.376972     74.663405           Regularly         Light      0.716409     5.925455             3                    9                    No     High School      Office   Engineer  6240.517690       Vegan        Cardio     Moderate          Moderate        No              High              5            High            Yes        No                  0               1.0                       5.5                 6.239340  healthy
2            3   46    Male  177.281966  80.687562  25.673050      25.673050   77.019151      25.587429   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164          Poor    5.829853           3.764406   2974.035375     1746.755144     19.702382           Regularly         Heavy      2.487900     4.371250             0                    1                    No          Master      Office    Teacher  3429.179266       Vegan        Cardio         High              Good       Yes              High              4        Moderate             No        No                  0               1.0                       5.5                 5.423737  healthy
3            4   32  Female  172.101255  63.142868  21.318480      21.318480   63.955440      21.177109  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316          Good    9.489693           0.889474   5321.539497     2034.193242     82.580050        Occasionally         Heavy      2.643335     4.116064            10                    4                    No          Master       Labor    Teacher  2618.503534  Vegetarian         Mixed          Low          Moderate        No              High              1         Unknown             No       Yes                  0               1.0                       5.5                 8.388611  healthy
4            5   60  Female  163.608816  40.000000  14.943302      14.943302   44.829907      14.844299   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514          Good    7.275450           2.901608   9791.376712     2386.210257     45.961322             Unknown         Heavy      1.968393     3.180087             9                    7                   Yes          Master  Unemployed     Doctor  3662.086276       Vegan       Unknown          Low          Moderate       Yes              High              1            High            Yes       Yes                  0               1.0                       5.5                 0.332622  healthy

In [250]:
cat_cols = [
    'gender',
    'diet_type',
    'exercise_type',
    'smoking_level'
]

for col in cat_cols:
    df[col] = df[col].astype(str)



for col in cat_cols:
    print(col)
    print(df[col].unique())
    print("="*50)

gender
['Male' 'Female']
==================================================
diet_type
['Vegan' 'Vegetarian' 'Omnivore' 'Keto']
==================================================
exercise_type
['Strength' 'Cardio' 'Mixed' 'Unknown']
==================================================
smoking_level
['Non-smoker' 'Light' 'Heavy']
==================================================

In [251]:
df.describe()

         survey_code            age         height         weight            bmi  bmi_estimated     bmi_scaled  bmi_corrected     waist_size  blood_pressure     heart_rate    cholesterol        glucose        insulin    sleep_hours     work_hours  physical_activity    daily_steps  calorie_intake   sugar_intake   water_intake    screen_time   stress_level  mental_health_score         income  meals_per_day  electrolyte_level  gene_marker_flag  environmental_risk_score  daily_supplement_dosage
count  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000  100000.000000      100000.000000  100000.000000   100000.000000  100000.000000  100000.000000  100000.000000  100000.000000        100000.000000  100000.000000  100000.000000           100000.0          100000.0                  100000.0            100000.000000
mean    50000.500000      48.525990     170.023707      70.064862      24.493876      24.493876      73.481627      24.494140      84.933043      119.977974      74.979964     189.966438      99.994538      14.987491       7.002008       8.001331           3.038344    7012.206098     2201.428579      60.047165       2.006373       6.021525       4.991600             5.004680    4035.287636       2.998720                0.0               1.0                       5.5                 0.015726
std     28867.657797      17.886768       9.982798      14.693667       5.951069       5.951069      17.853206       5.954184      12.040314       14.428246       9.219394      29.981934      19.982828       4.589596       1.496821       1.994723           1.884475    2383.082319      400.516318      19.966850       0.688868       2.933835       3.154997             3.164228    1846.503636       1.414786                0.0               0.0                       0.0                 5.764489
min         1.000000      18.000000     140.000000      40.000000       9.988495       9.988495      29.965484       9.893845      34.093185       59.128168      34.745092      58.410902      12.434931      -6.794483       3.000000       0.000000           0.000000    1000.000000      527.172360     -27.882444       0.500000       0.000000       0.000000             0.000000     500.000000       1.000000                0.0               1.0                       5.5                -9.999895
25%     25000.750000      33.000000     163.306615      59.856938      20.271405      20.271405      60.814215      20.271059      76.795185      110.815119      69.543894     169.667738      86.461401      12.324714       5.986781       6.651093           1.633799    5500.327842     1932.278165      46.504292       1.532011       3.971318       2.000000             2.000000    2796.061969       2.000000                0.0               1.0                       5.5                -4.980501
50%     50000.500000      48.000000     170.016778      69.924141      24.156734      24.156734      72.470201      24.151699      84.957139      119.951794      75.046211     190.044579      99.986834      14.983414       6.998164       8.004549           2.971222    7004.285450     2200.992765      60.047905       2.000659       5.991171       5.000000             5.000000    4004.601345       3.000000                0.0               1.0                       5.5                 0.015589
75%     75000.250000      64.000000     176.728920      80.027418      28.258696      28.258696      84.776088      28.247648      93.018713      129.185145      80.467128     210.222005     113.508722      17.663430       8.019219       9.353669           4.326500    8523.819577     2471.218160      73.476386       2.473047       8.024470       8.000000             8.000000    5219.230324       4.000000                0.0               1.0                       5.5                 5.008424
max    100000.000000      79.000000     210.000000     139.250894      59.234792      59.234792     177.704377      59.142646     133.153631      184.439195     114.136041     319.875613     183.883548      35.464749      12.000000      16.000000          11.631898   18064.969543     3949.019017     141.514522       5.000000      16.000000      10.000000            10.000000   12029.409353       5.000000                0.0               1.0                       5.5                 9.999966

In [252]:
print(df['target'].value_counts())
 
print(df['target'].value_counts(normalize=True))

target
healthy     70097
diseased    29903
Name: count, dtype: int64
target
healthy     0.70097
diseased    0.29903
Name: proportion, dtype: float64

In [253]:
# Menghapus kolom yang tidak diperlukan 
df = df.drop(columns=[
'survey_code',
'bmi_estimated','bmi_scaled','bmi_corrected',
'mental_health_score','mental_health_support',
'education_level','job_type','occupation',
'income','healthcare_access','insurance',
'sunlight_exposure','family_history','pet_owner',
'electrolyte_level','gene_marker_flag',
'environmental_risk_score','daily_supplement_dosage'
])

Feature engineering

In [254]:
category_cols = df.select_dtypes(include='category').columns

for col in category_cols:
    df[col] = df[col].astype(str)

In [255]:
# ============================================================
# FEATURE ENGINEERING
# Membuat fitur baru untuk meningkatkan performa model
# ============================================================

# ------------------------------------------------------------
# 1. BMI Category
# Mengelompokkan BMI berdasarkan standar WHO
# ------------------------------------------------------------
df['bmi_category'] = pd.cut(
    df['bmi'],
    bins=[0, 18.5, 25, 30, 100],
    labels=['underweight', 'normal', 'overweight', 'obese']
)

# ------------------------------------------------------------
# 2. Indikator Risiko Gaya Hidup
# ------------------------------------------------------------
df['high_sugar'] = (df['sugar_intake'] > 50).astype(int)
df['low_steps'] = (df['daily_steps'] < 5000).astype(int)
df['high_stress'] = (df['stress_level'] > 7).astype(int)
df['poor_sleep'] = (df['sleep_hours'] < 6).astype(int)
df['high_screen_time'] = (df['screen_time'] > 6).astype(int)
df['high_blood_pressure'] = (df['blood_pressure'] > 140).astype(int)
df['high_glucose'] = (df['glucose'] > 126).astype(int)
df['high_cholesterol'] = (df['cholesterol'] > 200).astype(int)

# ------------------------------------------------------------
# 3. Interaksi Antar Variabel
# ------------------------------------------------------------
df['bmi_x_age'] = df['bmi'] * df['age']
df['glucose_x_insulin'] = df['glucose'] * df['insulin']
df['stress_x_sleep'] = df['stress_level'] * df['sleep_hours']
df['steps_x_activity'] = df['daily_steps'] * df['physical_activity']
df['calorie_x_sugar'] = df['calorie_intake'] * df['sugar_intake']
df['waist_x_bmi'] = df['waist_size'] * df['bmi']

# ------------------------------------------------------------
# 4. Rasio Kesehatan
# ------------------------------------------------------------
df['calorie_per_meal'] = (
    df['calorie_intake'] / (df['meals_per_day'] + 1)
)

df['water_per_weight'] = (
    df['water_intake'] / (df['weight'] + 1)
)

df['steps_per_calorie'] = (
    df['daily_steps'] / (df['calorie_intake'] + 1)
)

df['sugar_per_meal'] = (
    df['sugar_intake'] / (df['meals_per_day'] + 1)
)

# ------------------------------------------------------------
# 5. Indeks Gaya Hidup
# ------------------------------------------------------------
df['lifestyle_risk_score'] = (
    df['high_sugar'] +
    df['low_steps'] +
    df['high_stress'] +
    df['poor_sleep'] +
    df['high_screen_time']
)

# ------------------------------------------------------------
# 6. Indeks Metabolik
# ------------------------------------------------------------
df['metabolic_risk_score'] = (
    df['high_blood_pressure'] +
    df['high_glucose'] +
    df['high_cholesterol']
)

# ------------------------------------------------------------
# 7. Kategori Usia
# ------------------------------------------------------------
df['age_group'] = pd.cut(
    df['age'],
    bins=[0, 30, 45, 60, 100],
    labels=['young', 'adult', 'middle_age', 'senior']
)

# ------------------------------------------------------------
# 8. Kategori Aktivitas
# ------------------------------------------------------------
df['activity_level'] = pd.cut(
    df['daily_steps'],
    bins=[0, 5000, 10000, 15000, 100000],
    labels=['sedentary', 'low', 'moderate', 'active']
)

# ------------------------------------------------------------
# 9. Kategori Durasi Tidur
# ------------------------------------------------------------
df['sleep_category'] = pd.cut(
    df['sleep_hours'],
    bins=[0, 5, 7, 9, 24],
    labels=['poor', 'average', 'good', 'excellent']
)

# ------------------------------------------------------------
# 10. Kategori Konsumsi Gula
# ------------------------------------------------------------
df['sugar_category'] = pd.cut(
    df['sugar_intake'],
    bins=[0, 25, 50, 75, 200],
    labels=['low', 'moderate', 'high', 'very_high']
)

# ------------------------------------------------------------
# 11. Kategori Tekanan Darah
# ------------------------------------------------------------
df['bp_category'] = pd.cut(
    df['blood_pressure'],
    bins=[0, 120, 140, 180, 300],
    labels=['normal', 'elevated', 'high', 'critical']
)

# ------------------------------------------------------------
# 12. Body Fat Proxy
# Estimasi sederhana dari komposisi tubuh
# ------------------------------------------------------------
df['body_fat_proxy'] = (
    (df['waist_size'] / df['height']) * 100
)

# ------------------------------------------------------------
# 13. Health Balance Score
# Semakin tinggi semakin sehat
# ------------------------------------------------------------
df['health_balance_score'] = (
    df['physical_activity'] * 2 +
    (df['daily_steps'] / 1000) +
    df['water_intake'] -
    (df['sugar_intake'] / 10) -
    df['stress_level']
)

print("Feature engineering selesai!")
print("Jumlah kolom sekarang:", df.shape[1])

Feature engineering selesai!
Jumlah kolom sekarang: 57

In [256]:
# Encode target
df['target'] = df['target'].map({
    'healthy': 0,
    'diseased': 1
})

In [257]:
X = df.drop('target', axis=1)
y = df['target']

In [258]:
print(df.select_dtypes(include='object').columns)

Index(['gender', 'sleep_quality', 'alcohol_consumption', 'smoking_level', 'diet_type', 'exercise_type', 'device_usage', 'caffeine_intake'], dtype='object')

Encoding Kategorikal

In [259]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Cari semua kolom object dan category
cat_cols = df.select_dtypes(include=['object', 'category']).columns

# Encode semua kolom object dan category
for col in cat_cols:
    df[col] = label_encoder.fit_transform(df[col].astype(str))

In [260]:
cat_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

In [261]:
df.head()

   age  gender      height     weight        bmi  waist_size  blood_pressure  heart_rate  cholesterol     glucose    insulin  sleep_hours  sleep_quality  work_hours  physical_activity   daily_steps  calorie_intake  sugar_intake  alcohol_consumption  smoking_level  water_intake  screen_time  stress_level  diet_type  exercise_type  device_usage  meals_per_day  caffeine_intake  target  bmi_category  high_sugar  low_steps  high_stress  poor_sleep  high_screen_time  high_blood_pressure  high_glucose  high_cholesterol    bmi_x_age  glucose_x_insulin  stress_x_sleep  steps_x_activity  calorie_x_sugar  waist_x_bmi  calorie_per_meal  water_per_weight  steps_per_calorie  sugar_per_meal  lifestyle_risk_score  metabolic_risk_score  age_group  activity_level  sleep_category  sugar_category  bp_category  body_fat_proxy  health_balance_score
0   56       1  173.416872  56.886640  18.915925   72.165130      118.264254   60.749825   214.580523  103.008176  14.983414     6.475885              1    7.671313           0.356918  13320.942595     2673.546960     44.476887                    2              2      1.694262     5.003963             2          2              2             0              5                1       0             0           0          0            0           0                 0                    0             0                 1  1059.291814        1543.414168       12.951769       4754.489210    118911.046147  1365.070201        445.591160          0.029269           4.980635        7.412815                     0                     1          1               2               0               2            3       41.613673              9.281353
1   69       0  163.207380  97.799859  36.716278   85.598889      117.917986   66.463696   115.794002  116.905134  10.131597     8.428410              2    9.515198           0.568219  11911.201401     2650.376972     74.663405                    1              1      0.716409     5.925455             3          2              0             2              5                0       0             1           1          0            0           0                 0                    0             0                 0  2533.423161        1184.435752       25.285230       6768.174923    197886.170005  3142.872578        441.729495          0.007251           4.492459       12.443901                     1                     0          2               2               2               0            3       52.447928              3.297709
2   46       1  177.281966  80.687562  25.673050   90.295030      123.073698   76.043212   138.134787   89.180302  14.983414     5.702164              3    5.829853           3.764406   2974.035375     1746.755144     19.702382                    1              0      2.487900     4.371250             0          2              0             0              4                1       0             2           0          1            0           1                 0                    0             0                 0  1180.960315        1336.225414        0.000000      11195.477297     34415.236950  2318.148859        349.351029          0.030456           1.701632        3.940476                     2                     0          1               3               0               1            1       50.933004             11.020510
3   32       0  172.101255  63.142868  21.318480  100.504211      148.173453   68.781981   203.017447  128.375798  18.733179     5.188316              2    9.489693           0.889474   5321.539497     2034.193242     82.580050                    0              0      2.643335     4.116064            10          3              1             1              1                2       0             0           1          0            1           1                 0                    1             1                 1   682.191355        2404.886856       51.883163       4733.372495    167983.779088  2142.596991       1017.096621          0.041210           2.614759       41.290025                     3                     3          0               1               0               4            2       58.398302             -8.514182
4   60       0  163.608816  40.000000  14.943302   69.021150      150.613181   92.335358   200.412439   94.813332  16.038701     7.912514              2    7.275450           2.901608   9791.376712     2386.210257     45.961322                    2              0      1.968393     3.180087             9          2              3             1              1                0       0             3           0          0            1           0                 0                    1             0                 1   896.598146        1520.682727       71.212622      28410.738309    109673.376954  1031.403918       1193.105128          0.048010           4.101598       22.980661                     1                     2          1               1               2               2            2       42.186694              3.966854

In [262]:
df['target'].value_counts()

target
0    70097
1    29903
Name: count, dtype: int64

In [263]:
# ============================================================
# SPLIT DATA
# ============================================================

from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [264]:
# Mengecek data sebelum split
print(x_train.shape)

(80000, 56)

Mengatasi Imbalanced Data

In [265]:
# ============================================================
# INSTALL
# ============================================================

!pip install imbalanced-learn

# ============================================================
# IMPORT
# ============================================================

from imblearn.over_sampling import RandomOverSampler

# ============================================================
# CEK DISTRIBUSI SEBELUM
# ============================================================

print("Distribusi target sebelum Oversampling:\n")

print(y_train.value_counts())

# ============================================================
# OVERSAMPLING
# ============================================================

oversample = RandomOverSampler(
    sampling_strategy='auto',
    random_state=42
)

x_train_over, y_train_over = oversample.fit_resample(
    x_train,
    y_train
)

# ============================================================
# CEK DISTRIBUSI SETELAH
# ============================================================

print("\nDistribusi target setelah Oversampling:\n")

print(y_train_over.value_counts())

Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)
Distribusi target sebelum Oversampling:

target
0    56078
1    23922
Name: count, dtype: int64

Distribusi target setelah Oversampling:

target
1    56078
0    56078
Name: count, dtype: int64

In [266]:
# Mengecek data setelah oversampling
print(x_train_over.shape)

(112156, 56)

In [267]:

# ============================================================
# MODEL DASAR
# ============================================================

cat_model = CatBoostClassifier(
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=100
)

# ============================================================
# PARAMETER YANG DITUNING (LEBIH RINGAN)
# ============================================================

param_grid = {
    'depth': [5, 6],
    'learning_rate': [0.02, 0.03],
    'l2_leaf_reg': [10, 15],
    'random_strength': [5, 10],
    'bagging_temperature': [1, 3],
    'iterations': [1000]
}

# ============================================================
# GRID SEARCH
# ============================================================

grid_result = cat_model.grid_search(
    param_grid=param_grid,
    X=x_train_over,
    y=y_train_over,
    cv=3,
    partition_random_seed=42,
    verbose=True
)

# ============================================================
# PARAMETER TERBAIK
# ============================================================

print("\nBest Parameters:")
print(grid_result['params'])

0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 47ms	remaining: 47s
100:	learn: 0.5697068	test: 0.5361706	best: 0.5388838 (65)	total: 5.17s	remaining: 46s
200:	learn: 0.5797175	test: 0.5354833	best: 0.5391050 (175)	total: 8.93s	remaining: 35.5s
300:	learn: 0.5852723	test: 0.5390569	best: 0.5391050 (175)	total: 12.6s	remaining: 29.3s
400:	learn: 0.5921227	test: 0.5395808	best: 0.5400480 (368)	total: 17.7s	remaining: 26.4s
500:	learn: 0.6005477	test: 0.5444113	best: 0.5451794 (498)	total: 21.4s	remaining: 21.3s
600:	learn: 0.6081453	test: 0.5495407	best: 0.5495407 (600)	total: 25.1s	remaining: 16.7s
700:	learn: 0.6201490	test: 0.5564800	best: 0.5564800 (700)	total: 29.9s	remaining: 12.8s
800:	learn: 0.6366767	test: 0.5641823	best: 0.5641823 (800)	total: 33.5s	remaining: 8.32s
900:	learn: 0.6490233	test: 0.5688716	best: 0.5698081 (892)	total: 37.1s	remaining: 4.08s
999:	learn: 0.6576786	test: 0.5699845	best: 0.5703638 (944)	total: 41.9s	remaining: 0us

bestTest = 0.5703637977
bestIteration = 944

0:	loss: 0.5703638	best: 0.5703638 (0)	total: 42.5s	remaining: 21m 56s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 37.3ms	remaining: 37.3s
100:	learn: 0.5667693	test: 0.5293209	best: 0.5366703 (26)	total: 3.79s	remaining: 33.7s
200:	learn: 0.5831666	test: 0.5301258	best: 0.5366703 (26)	total: 7.54s	remaining: 30s
300:	learn: 0.5950879	test: 0.5431749	best: 0.5443032 (291)	total: 12.6s	remaining: 29.2s
400:	learn: 0.6044116	test: 0.5477899	best: 0.5494826 (394)	total: 16.3s	remaining: 24.3s
500:	learn: 0.6244519	test: 0.5555457	best: 0.5564010 (466)	total: 20s	remaining: 19.9s
600:	learn: 0.6426731	test: 0.5633093	best: 0.5633093 (600)	total: 24.8s	remaining: 16.4s
700:	learn: 0.6580719	test: 0.5721590	best: 0.5721590 (700)	total: 28.6s	remaining: 12.2s
800:	learn: 0.6689099	test: 0.5752494	best: 0.5765464 (794)	total: 32.3s	remaining: 8.03s
900:	learn: 0.6787304	test: 0.5793963	best: 0.5796730 (897)	total: 36.7s	remaining: 4.04s
999:	learn: 0.6871994	test: 0.5829204	best: 0.5848982 (982)	total: 40.8s	remaining: 0us

bestTest = 0.5848981576
bestIteration = 982

1:	loss: 0.5848982	best: 0.5848982 (1)	total: 1m 23s	remaining: 20m 50s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 35.3ms	remaining: 35.2s
100:	learn: 0.5650663	test: 0.5356001	best: 0.5373134 (82)	total: 3.88s	remaining: 34.6s
200:	learn: 0.5790663	test: 0.5377111	best: 0.5443855 (149)	total: 8.13s	remaining: 32.3s
300:	learn: 0.5913612	test: 0.5439483	best: 0.5449792 (277)	total: 12.8s	remaining: 29.8s
400:	learn: 0.5967758	test: 0.5443740	best: 0.5458492 (394)	total: 16.6s	remaining: 24.8s
500:	learn: 0.6041768	test: 0.5479099	best: 0.5493619 (460)	total: 20.7s	remaining: 20.6s
600:	learn: 0.6112042	test: 0.5501578	best: 0.5502222 (577)	total: 25.5s	remaining: 16.9s
700:	learn: 0.6221661	test: 0.5539268	best: 0.5551020 (692)	total: 29.2s	remaining: 12.5s
800:	learn: 0.6334213	test: 0.5592009	best: 0.5603655 (799)	total: 32.8s	remaining: 8.14s
900:	learn: 0.6471863	test: 0.5686353	best: 0.5698250 (896)	total: 37.8s	remaining: 4.15s
999:	learn: 0.6588524	test: 0.5746934	best: 0.5762533 (995)	total: 41.4s	remaining: 0us

bestTest = 0.5762532516
bestIteration = 995

2:	loss: 0.5762533	best: 0.5848982 (1)	total: 2m 4s	remaining: 20m 6s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 37.1ms	remaining: 37s
100:	learn: 0.5749618	test: 0.5386875	best: 0.5413974 (84)	total: 3.82s	remaining: 34s
200:	learn: 0.5866776	test: 0.5391980	best: 0.5413974 (84)	total: 8.91s	remaining: 35.4s
300:	learn: 0.5972162	test: 0.5445290	best: 0.5470456 (281)	total: 12.6s	remaining: 29.3s
400:	learn: 0.6073643	test: 0.5472967	best: 0.5495563 (371)	total: 16.4s	remaining: 24.5s
500:	learn: 0.6248407	test: 0.5559196	best: 0.5566563 (493)	total: 21.3s	remaining: 21.3s
600:	learn: 0.6439425	test: 0.5655245	best: 0.5655245 (600)	total: 25s	remaining: 16.6s
700:	learn: 0.6572591	test: 0.5713274	best: 0.5741289 (689)	total: 28.7s	remaining: 12.2s
800:	learn: 0.6694010	test: 0.5764815	best: 0.5771872 (796)	total: 33.6s	remaining: 8.34s
900:	learn: 0.6798771	test: 0.5812412	best: 0.5820321 (879)	total: 37.1s	remaining: 4.08s
999:	learn: 0.6895797	test: 0.5887511	best: 0.5899548 (997)	total: 40.8s	remaining: 0us

bestTest = 0.5899548233
bestIteration = 997

3:	loss: 0.5899548	best: 0.5899548 (3)	total: 2m 45s	remaining: 19m 19s
0:	learn: 0.4031414	test: 0.3937042	best: 0.3937042 (0)	total: 39.2ms	remaining: 39.2s
100:	learn: 0.5659653	test: 0.5323931	best: 0.5355100 (92)	total: 5.1s	remaining: 45.4s
200:	learn: 0.5813664	test: 0.5383260	best: 0.5383260 (200)	total: 8.84s	remaining: 35.1s
300:	learn: 0.5868947	test: 0.5370330	best: 0.5413693 (274)	total: 12.6s	remaining: 29.3s
400:	learn: 0.5939833	test: 0.5426555	best: 0.5439323 (384)	total: 17.4s	remaining: 26s
500:	learn: 0.5997036	test: 0.5446121	best: 0.5449408 (498)	total: 21.4s	remaining: 21.3s
600:	learn: 0.6053299	test: 0.5447629	best: 0.5458720 (530)	total: 25.1s	remaining: 16.7s
700:	learn: 0.6154136	test: 0.5490283	best: 0.5490283 (700)	total: 29.4s	remaining: 12.6s
800:	learn: 0.6295846	test: 0.5582486	best: 0.5593633 (794)	total: 33.6s	remaining: 8.36s
900:	learn: 0.6430139	test: 0.5641658	best: 0.5651638 (898)	total: 37.2s	remaining: 4.09s
999:	learn: 0.6552946	test: 0.5692844	best: 0.5697018 (996)	total: 40.8s	remaining: 0us

bestTest = 0.5697017822
bestIteration = 996

4:	loss: 0.5697018	best: 0.5899548 (3)	total: 3m 26s	remaining: 18m 35s
0:	learn: 0.4031414	test: 0.3937042	best: 0.3937042 (0)	total: 69.9ms	remaining: 1m 9s
100:	learn: 0.5655469	test: 0.5309358	best: 0.5329273 (96)	total: 5.11s	remaining: 45.5s
200:	learn: 0.5794250	test: 0.5334813	best: 0.5339965 (199)	total: 8.92s	remaining: 35.5s
300:	learn: 0.5921563	test: 0.5398898	best: 0.5398898 (300)	total: 12.7s	remaining: 29.5s
400:	learn: 0.6016984	test: 0.5449224	best: 0.5453981 (387)	total: 17.7s	remaining: 26.4s
500:	learn: 0.6175526	test: 0.5562902	best: 0.5562902 (500)	total: 21.4s	remaining: 21.3s
600:	learn: 0.6398026	test: 0.5647329	best: 0.5654117 (594)	total: 24.9s	remaining: 16.6s
700:	learn: 0.6556508	test: 0.5723376	best: 0.5739883 (684)	total: 30s	remaining: 12.8s
800:	learn: 0.6663283	test: 0.5743871	best: 0.5767717 (767)	total: 33.7s	remaining: 8.36s
900:	learn: 0.6780637	test: 0.5808733	best: 0.5812690 (898)	total: 37.3s	remaining: 4.1s
999:	learn: 0.6848008	test: 0.5840983	best: 0.5851497 (984)	total: 42.2s	remaining: 0us

bestTest = 0.585149743
bestIteration = 984

5:	loss: 0.5851497	best: 0.5899548 (3)	total: 4m 8s	remaining: 17m 58s
0:	learn: 0.4031414	test: 0.3937042	best: 0.3937042 (0)	total: 37.6ms	remaining: 37.6s
100:	learn: 0.5687049	test: 0.5363373	best: 0.5408976 (88)	total: 3.81s	remaining: 33.9s
200:	learn: 0.5778696	test: 0.5398503	best: 0.5408976 (88)	total: 7.54s	remaining: 30s
300:	learn: 0.5858733	test: 0.5417751	best: 0.5428420 (249)	total: 12.6s	remaining: 29.3s
400:	learn: 0.5953052	test: 0.5447399	best: 0.5463922 (379)	total: 16.3s	remaining: 24.4s
500:	learn: 0.5990083	test: 0.5479537	best: 0.5479537 (500)	total: 20.1s	remaining: 20s
600:	learn: 0.6028744	test: 0.5492646	best: 0.5492646 (600)	total: 25.1s	remaining: 16.7s
700:	learn: 0.6130156	test: 0.5491654	best: 0.5504449 (616)	total: 28.8s	remaining: 12.3s
800:	learn: 0.6269107	test: 0.5593717	best: 0.5597445 (799)	total: 32.4s	remaining: 8.05s
900:	learn: 0.6400009	test: 0.5638735	best: 0.5642115 (899)	total: 36.8s	remaining: 4.05s
999:	learn: 0.6511458	test: 0.5716814	best: 0.5719084 (995)	total: 40.9s	remaining: 0us

bestTest = 0.5719084239
bestIteration = 995

6:	loss: 0.5719084	best: 0.5899548 (3)	total: 4m 49s	remaining: 17m 14s
0:	learn: 0.4031414	test: 0.3937042	best: 0.3937042 (0)	total: 37.9ms	remaining: 37.9s
100:	learn: 0.5678491	test: 0.5327107	best: 0.5392874 (83)	total: 3.74s	remaining: 33.3s
200:	learn: 0.5805939	test: 0.5384309	best: 0.5392874 (83)	total: 7.87s	remaining: 31.3s
300:	learn: 0.5899370	test: 0.5420619	best: 0.5435023 (276)	total: 12.6s	remaining: 29.2s
400:	learn: 0.5984771	test: 0.5441966	best: 0.5445031 (398)	total: 16.4s	remaining: 24.4s
500:	learn: 0.6142799	test: 0.5544414	best: 0.5544414 (500)	total: 20.1s	remaining: 20.1s
600:	learn: 0.6382439	test: 0.5639737	best: 0.5648034 (596)	total: 25s	remaining: 16.6s
700:	learn: 0.6514354	test: 0.5674021	best: 0.5684693 (687)	total: 28.6s	remaining: 12.2s
800:	learn: 0.6641514	test: 0.5719459	best: 0.5722849 (745)	total: 32.2s	remaining: 8s
900:	learn: 0.6752519	test: 0.5780787	best: 0.5785212 (899)	total: 37.1s	remaining: 4.08s
999:	learn: 0.6851331	test: 0.5843753	best: 0.5854479 (982)	total: 40.7s	remaining: 0us

bestTest = 0.585447943
bestIteration = 982

7:	loss: 0.5854479	best: 0.5899548 (3)	total: 5m 30s	remaining: 16m 31s
0:	learn: 0.5146266	test: 0.5106137	best: 0.5106137 (0)	total: 49.1ms	remaining: 49.1s
100:	learn: 0.5953551	test: 0.5490733	best: 0.5525377 (97)	total: 4.57s	remaining: 40.7s
200:	learn: 0.6143788	test: 0.5511308	best: 0.5530413 (114)	total: 10.4s	remaining: 41.3s
300:	learn: 0.6302752	test: 0.5631301	best: 0.5634516 (297)	total: 14.9s	remaining: 34.5s
400:	learn: 0.6423059	test: 0.5638880	best: 0.5658211 (381)	total: 20.7s	remaining: 30.9s
500:	learn: 0.6533301	test: 0.5700457	best: 0.5703760 (499)	total: 25.2s	remaining: 25.1s
600:	learn: 0.6615220	test: 0.5710730	best: 0.5714032 (599)	total: 29.7s	remaining: 19.7s
700:	learn: 0.6758094	test: 0.5797463	best: 0.5798817 (698)	total: 35.4s	remaining: 15.1s
800:	learn: 0.6903124	test: 0.5872333	best: 0.5880527 (797)	total: 39.5s	remaining: 9.82s
900:	learn: 0.7017291	test: 0.5936822	best: 0.5941971 (893)	total: 44.2s	remaining: 4.86s
999:	learn: 0.7130456	test: 0.5970865	best: 0.5970865 (999)	total: 49.4s	remaining: 0us

bestTest = 0.5970865163
bestIteration = 999

8:	loss: 0.5970865	best: 0.5970865 (8)	total: 6m 19s	remaining: 16m 11s
0:	learn: 0.5146266	test: 0.5106137	best: 0.5106137 (0)	total: 64.3ms	remaining: 1m 4s
100:	learn: 0.5967672	test: 0.5426754	best: 0.5431423 (99)	total: 4.48s	remaining: 39.9s
200:	learn: 0.6236110	test: 0.5536378	best: 0.5536378 (200)	total: 10.3s	remaining: 40.8s
300:	learn: 0.6396386	test: 0.5593205	best: 0.5593205 (300)	total: 14.8s	remaining: 34.4s
400:	learn: 0.6535723	test: 0.5693865	best: 0.5693865 (400)	total: 19.3s	remaining: 28.9s
500:	learn: 0.6784473	test: 0.5876025	best: 0.5878101 (499)	total: 25.3s	remaining: 25.2s
600:	learn: 0.6993248	test: 0.5956736	best: 0.5965175 (594)	total: 29.7s	remaining: 19.7s
700:	learn: 0.7139773	test: 0.6009709	best: 0.6010404 (698)	total: 35s	remaining: 14.9s
800:	learn: 0.7255763	test: 0.6068679	best: 0.6070626 (778)	total: 39.8s	remaining: 9.88s
900:	learn: 0.7369311	test: 0.6114949	best: 0.6119793 (886)	total: 44.2s	remaining: 4.86s
999:	learn: 0.7465636	test: 0.6164402	best: 0.6168216 (981)	total: 49.8s	remaining: 0us

bestTest = 0.6168216025
bestIteration = 981

9:	loss: 0.6168216	best: 0.6168216 (9)	total: 7m 9s	remaining: 15m 45s
0:	learn: 0.5146266	test: 0.5106137	best: 0.5106137 (0)	total: 46.7ms	remaining: 46.7s
100:	learn: 0.5925400	test: 0.5408476	best: 0.5425008 (91)	total: 4.51s	remaining: 40.2s
200:	learn: 0.6158938	test: 0.5497470	best: 0.5497470 (200)	total: 9.13s	remaining: 36.3s
300:	learn: 0.6320003	test: 0.5566452	best: 0.5590189 (298)	total: 14.4s	remaining: 33.5s
400:	learn: 0.6413760	test: 0.5629584	best: 0.5629584 (400)	total: 19s	remaining: 28.4s
500:	learn: 0.6524181	test: 0.5668815	best: 0.5681435 (497)	total: 24.9s	remaining: 24.8s
600:	learn: 0.6638793	test: 0.5741546	best: 0.5747902 (580)	total: 29.4s	remaining: 19.5s
700:	learn: 0.6753898	test: 0.5834990	best: 0.5844523 (697)	total: 33.6s	remaining: 14.3s
800:	learn: 0.6919856	test: 0.5916461	best: 0.5921586 (798)	total: 39s	remaining: 9.7s
900:	learn: 0.7030294	test: 0.5951686	best: 0.5959949 (887)	total: 43.3s	remaining: 4.76s
999:	learn: 0.7115521	test: 0.5989776	best: 0.5989776 (999)	total: 47.8s	remaining: 0us

bestTest = 0.5989775506
bestIteration = 999

10:	loss: 0.5989776	best: 0.6168216 (9)	total: 7m 57s	remaining: 15m 11s
0:	learn: 0.5146266	test: 0.5106137	best: 0.5106137 (0)	total: 87.4ms	remaining: 1m 27s
100:	learn: 0.5927985	test: 0.5376525	best: 0.5422984 (68)	total: 5.47s	remaining: 48.7s
200:	learn: 0.6228269	test: 0.5521570	best: 0.5541469 (188)	total: 9.95s	remaining: 39.5s
300:	learn: 0.6381638	test: 0.5566021	best: 0.5588782 (262)	total: 15.7s	remaining: 36.4s
400:	learn: 0.6550644	test: 0.5687984	best: 0.5690399 (399)	total: 20s	remaining: 29.9s
500:	learn: 0.6733930	test: 0.5715560	best: 0.5733974 (488)	total: 24.1s	remaining: 24s
600:	learn: 0.6942147	test: 0.5869777	best: 0.5878753 (597)	total: 29.5s	remaining: 19.6s
700:	learn: 0.7105362	test: 0.5965099	best: 0.5979144 (698)	total: 33.7s	remaining: 14.4s
800:	learn: 0.7241192	test: 0.6046884	best: 0.6061978 (780)	total: 38s	remaining: 9.45s
900:	learn: 0.7339721	test: 0.6100458	best: 0.6114740 (889)	total: 43.3s	remaining: 4.76s
999:	learn: 0.7455810	test: 0.6177866	best: 0.6179446 (998)	total: 47.5s	remaining: 0us

bestTest = 0.6179446219
bestIteration = 998

11:	loss: 0.6179446	best: 0.6179446 (11)	total: 8m 45s	remaining: 14m 35s
0:	learn: 0.4847544	test: 0.4789142	best: 0.4789142 (0)	total: 76.3ms	remaining: 1m 16s
100:	learn: 0.5931778	test: 0.5472628	best: 0.5472628 (100)	total: 5.62s	remaining: 50s
200:	learn: 0.6143136	test: 0.5566013	best: 0.5566013 (200)	total: 9.98s	remaining: 39.7s
300:	learn: 0.6224836	test: 0.5562282	best: 0.5585713 (284)	total: 14.5s	remaining: 33.6s
400:	learn: 0.6322839	test: 0.5610178	best: 0.5627958 (374)	total: 20.2s	remaining: 30.2s
500:	learn: 0.6429088	test: 0.5622757	best: 0.5646018 (495)	total: 24.7s	remaining: 24.6s
600:	learn: 0.6516041	test: 0.5664801	best: 0.5673923 (582)	total: 29.5s	remaining: 19.6s
700:	learn: 0.6665999	test: 0.5721647	best: 0.5724175 (694)	total: 34.6s	remaining: 14.8s
800:	learn: 0.6844541	test: 0.5803904	best: 0.5803904 (800)	total: 38.9s	remaining: 9.66s
900:	learn: 0.6976321	test: 0.5899230	best: 0.5911082 (875)	total: 44.4s	remaining: 4.88s
999:	learn: 0.7103742	test: 0.5966294	best: 0.5981176 (972)	total: 48.5s	remaining: 0us

bestTest = 0.5981176263
bestIteration = 972

12:	loss: 0.5981176	best: 0.6179446 (11)	total: 9m 33s	remaining: 13m 58s
0:	learn: 0.4847544	test: 0.4789142	best: 0.4789142 (0)	total: 47.7ms	remaining: 47.6s
100:	learn: 0.5974813	test: 0.5491735	best: 0.5491735 (100)	total: 4.45s	remaining: 39.6s
200:	learn: 0.6176988	test: 0.5547561	best: 0.5581559 (178)	total: 9.94s	remaining: 39.5s
300:	learn: 0.6341205	test: 0.5611644	best: 0.5630223 (283)	total: 14.4s	remaining: 33.4s
400:	learn: 0.6506693	test: 0.5659730	best: 0.5661473 (398)	total: 19.1s	remaining: 28.5s
500:	learn: 0.6674064	test: 0.5767446	best: 0.5773005 (498)	total: 24.5s	remaining: 24.4s
600:	learn: 0.6907113	test: 0.5843113	best: 0.5859985 (596)	total: 28.6s	remaining: 19s
700:	learn: 0.7060528	test: 0.5935067	best: 0.5939651 (691)	total: 34.2s	remaining: 14.6s
800:	learn: 0.7197361	test: 0.6015642	best: 0.6026695 (798)	total: 38.4s	remaining: 9.54s
900:	learn: 0.7304523	test: 0.6042229	best: 0.6045935 (875)	total: 42.6s	remaining: 4.68s
999:	learn: 0.7427988	test: 0.6147994	best: 0.6154322 (995)	total: 48.1s	remaining: 0us

bestTest = 0.6154322079
bestIteration = 995

13:	loss: 0.6154322	best: 0.6179446 (11)	total: 10m 22s	remaining: 13m 19s
0:	learn: 0.4847544	test: 0.4789142	best: 0.4789142 (0)	total: 44.1ms	remaining: 44.1s
100:	learn: 0.5935064	test: 0.5385499	best: 0.5417051 (90)	total: 4.32s	remaining: 38.5s
200:	learn: 0.6139143	test: 0.5504644	best: 0.5505153 (197)	total: 8.63s	remaining: 34.3s
300:	learn: 0.6261512	test: 0.5524608	best: 0.5531821 (297)	total: 14.2s	remaining: 33s
400:	learn: 0.6371875	test: 0.5569095	best: 0.5571920 (393)	total: 18.7s	remaining: 27.9s
500:	learn: 0.6430760	test: 0.5593866	best: 0.5610593 (428)	total: 24.3s	remaining: 24.2s
600:	learn: 0.6517694	test: 0.5645140	best: 0.5654005 (591)	total: 28.7s	remaining: 19.1s
700:	learn: 0.6657578	test: 0.5718339	best: 0.5721875 (674)	total: 33.1s	remaining: 14.1s
800:	learn: 0.6815748	test: 0.5779881	best: 0.5787309 (794)	total: 38.5s	remaining: 9.56s
900:	learn: 0.6971229	test: 0.5881989	best: 0.5883602 (898)	total: 42.6s	remaining: 4.68s
999:	learn: 0.7069034	test: 0.5920744	best: 0.5923237 (997)	total: 46.8s	remaining: 0us

bestTest = 0.5923236974
bestIteration = 997

14:	loss: 0.5923237	best: 0.6179446 (11)	total: 11m 8s	remaining: 12m 38s
0:	learn: 0.4847544	test: 0.4789142	best: 0.4789142 (0)	total: 44ms	remaining: 43.9s
100:	learn: 0.5953154	test: 0.5475329	best: 0.5475329 (100)	total: 5.72s	remaining: 50.9s
200:	learn: 0.6155180	test: 0.5506821	best: 0.5510014 (197)	total: 10.2s	remaining: 40.5s
300:	learn: 0.6340921	test: 0.5611012	best: 0.5611012 (300)	total: 15.8s	remaining: 36.8s
400:	learn: 0.6485651	test: 0.5688203	best: 0.5700252 (396)	total: 20.3s	remaining: 30.3s
500:	learn: 0.6693132	test: 0.5736124	best: 0.5746524 (494)	total: 24.5s	remaining: 24.4s
600:	learn: 0.6896536	test: 0.5894942	best: 0.5894942 (600)	total: 30s	remaining: 19.9s
700:	learn: 0.7062668	test: 0.5975739	best: 0.5993373 (696)	total: 34.2s	remaining: 14.6s
800:	learn: 0.7208838	test: 0.6080360	best: 0.6090981 (794)	total: 38.3s	remaining: 9.53s
900:	learn: 0.7291866	test: 0.6102070	best: 0.6116470 (880)	total: 43.9s	remaining: 4.83s
999:	learn: 0.7422722	test: 0.6149565	best: 0.6168768 (980)	total: 48.2s	remaining: 0us

bestTest = 0.6168768186
bestIteration = 980

15:	loss: 0.6168768	best: 0.6179446 (11)	total: 11m 57s	remaining: 11m 57s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 36.3ms	remaining: 36.3s
100:	learn: 0.5697068	test: 0.5361706	best: 0.5388838 (65)	total: 3.99s	remaining: 35.5s
200:	learn: 0.5797175	test: 0.5354833	best: 0.5391050 (175)	total: 8.51s	remaining: 33.8s
300:	learn: 0.5852723	test: 0.5390569	best: 0.5391050 (175)	total: 12.2s	remaining: 28.3s
400:	learn: 0.5921227	test: 0.5395808	best: 0.5400480 (368)	total: 15.8s	remaining: 23.6s
500:	learn: 0.6005477	test: 0.5444113	best: 0.5451794 (498)	total: 20.8s	remaining: 20.7s
600:	learn: 0.6081453	test: 0.5495407	best: 0.5495407 (600)	total: 24.3s	remaining: 16.2s
700:	learn: 0.6201490	test: 0.5564800	best: 0.5564800 (700)	total: 27.9s	remaining: 11.9s
800:	learn: 0.6366767	test: 0.5641823	best: 0.5641823 (800)	total: 32.8s	remaining: 8.15s
900:	learn: 0.6490233	test: 0.5688716	best: 0.5698081 (892)	total: 36.4s	remaining: 4s
999:	learn: 0.6576786	test: 0.5699845	best: 0.5703638 (944)	total: 39.9s	remaining: 0us

bestTest = 0.5703637977
bestIteration = 944

16:	loss: 0.5703638	best: 0.6179446 (11)	total: 12m 37s	remaining: 11m 8s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 38.3ms	remaining: 38.2s
100:	learn: 0.5667693	test: 0.5293209	best: 0.5366703 (26)	total: 5.13s	remaining: 45.6s
200:	learn: 0.5831666	test: 0.5301258	best: 0.5366703 (26)	total: 8.85s	remaining: 35.2s
300:	learn: 0.5950879	test: 0.5431749	best: 0.5443032 (291)	total: 12.5s	remaining: 29.1s
400:	learn: 0.6044116	test: 0.5477899	best: 0.5494826 (394)	total: 17.2s	remaining: 25.7s
500:	learn: 0.6244519	test: 0.5555457	best: 0.5564010 (466)	total: 21s	remaining: 20.9s
600:	learn: 0.6426731	test: 0.5633093	best: 0.5633093 (600)	total: 24.6s	remaining: 16.3s
700:	learn: 0.6580719	test: 0.5721590	best: 0.5721590 (700)	total: 28.4s	remaining: 12.1s
800:	learn: 0.6689099	test: 0.5752494	best: 0.5765464 (794)	total: 32.9s	remaining: 8.18s
900:	learn: 0.6787304	test: 0.5793963	best: 0.5796730 (897)	total: 36.6s	remaining: 4.02s
999:	learn: 0.6871994	test: 0.5829204	best: 0.5848982 (982)	total: 40.1s	remaining: 0us

bestTest = 0.5848981576
bestIteration = 982

17:	loss: 0.5848982	best: 0.6179446 (11)	total: 13m 17s	remaining: 10m 20s
0:	learn: 0.5233558	test: 0.5207908	best: 0.5207908 (0)	total: 37ms	remaining: 37s
100:	learn: 0.5650663	test: 0.5356001	best: 0.5373134 (82)	total: 5.14s	remaining: 45.8s

In [268]:
best_model = CatBoostClassifier(
    **grid_result['params'],
    loss_function='Logloss',
    eval_metric='F1',
    random_state=42,
    verbose=100
)

best_model.fit(
    x_train_over,
    y_train_over
)

0:	learn: 0.4150345	total: 50.2ms	remaining: 50.1s
100:	learn: 0.5945199	total: 5.06s	remaining: 45s
200:	learn: 0.6151050	total: 11.4s	remaining: 45.3s
300:	learn: 0.6349198	total: 16.6s	remaining: 38.5s
400:	learn: 0.6460567	total: 22.6s	remaining: 33.7s
500:	learn: 0.6684400	total: 27.8s	remaining: 27.7s
600:	learn: 0.6876579	total: 32.6s	remaining: 21.6s
700:	learn: 0.7029830	total: 38.6s	remaining: 16.5s
800:	learn: 0.7171706	total: 43.4s	remaining: 10.8s
900:	learn: 0.7254815	total: 49.3s	remaining: 5.41s
999:	learn: 0.7344476	total: 54s	remaining: 0us

CatBoostClassifier(bagging_temperature=1, depth=6, eval_metric='F1', iterations=1000, l2_leaf_reg=15, learning_rate=0.03, loss_function='Logloss', random_state=42, random_strength=5, verbose=100)

Tes Data

In [269]:
# Prediksi langsung
y_pred = best_model.predict(x_test)

# Evaluasi
print(classification_report(y_test, y_pred))

cat_acc = accuracy_score(y_test, y_pred)

print("Akurasi CatBoost = {:.2f}%".format(cat_acc*100))

              precision    recall  f1-score   support

           0       0.71      0.62      0.66     14019
           1       0.31      0.39      0.34      5981

    accuracy                           0.55     20000
   macro avg       0.51      0.51      0.50     20000
weighted avg       0.59      0.55      0.57     20000

Akurasi CatBoost = 55.16%